// Freeze successful bounded preparation, before the one real task-run.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
const local=path.resolve('local/plain-mui-18141'),dev='development/plain-mui-18141',get=p=>JSON.parse(fs.readFileSync(p)),hash=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex'),save=(p,x)=>fs.writeFileSync(p,JSON.stringify(x,null,2)+'\n',{flag:'wx'});
const calibration=get(local+'/calibration-2/summary.json'),preflight=get(local+'/preflight/verification.json');assert.equal(calibration.calibration_passed,true);assert.equal(preflight.passed,true);assert.deepEqual([...calibration.created_containers].sort(),[...calibration.removed_containers].sort());
const names=execFileSync('docker',['ps','--format','{{.Names}}'],{encoding:'utf8'}).trim().split('\n').filter(Boolean);assert.ok(!names.some(n=>/^(template-dev-|preservation-|polybench-)/.test(n)));
const f=get(local+'/prepared.json');f.experimentKind='plain-mui-18141';f.controlsPassed=true;f.authorIsolationPassed=true;
const files=[...['PLAN.md','fe-manifest.json','id-observation.test.js','prepare.py','prepare-input.mjs','preflight.mjs','freeze.mjs','verify.py'].map(n=>dev+'/'+n),'development/polybench-pilot/run.mjs','development/native-task-ab/run-comparison.mjs','development/native-task-abc/native-run.mjs','development/native-task-integrated/container-session.mjs','development/native-task-integrated/container-relay.mjs','development/native-task-utility/container/stop-workload.mjs','development/polybench-pilot/capture.mjs','development/polybench-pilot/dependencies.mjs','development/native-output-retention/output-files.mjs','development/native-task-ab/extract-candidate.py','development/native-task-offline/build.json','development/polybench-pilot/two-world-diagnostic/driver.py',f.toolchain+'/package/bin/opencode'];
for(const file of files)f.files[path.resolve(file)]=hash(file);
for(const name of ['freeze.json','freeze-commit.json','scheduling-paused.json','outcome.json']){const file=path.resolve('local/polybench-pilot/batch/'+name);f.files[file]=hash(file);}
const input=get(local+'/input-receipt.json'),task=input.task;
for(const image of [task.authorImage,task.officialImage.digest]){const actual=execFileSync('docker',['image','inspect',image,'--format','{{.Id}}'],{encoding:'utf8'}).trim();assert.equal(actual,image===task.authorImage?task.authorImage:task.officialImage.id);}
const old=get('development/plain-contract-admission/receipts.json');for(const item of old.preserved_local_stop_state)assert.equal(hash(item.path),item.sha256);
fs.mkdirSync(local+'/batch',{mode:0o700});save(local+'/batch/freeze.json',f);
const safe=structuredClone(calibration);delete safe.created_containers;delete safe.removed_containers;save(dev+'/calibration.json',safe);save(dev+'/preflight.json',preflight);
save(dev+'/manifest.json',{version:1,stage:'frozen_before_model_requests',startingHead:'711f91185eca48059ff4fcd0d031cf3963501a5a',freezeSha256:hash(local+'/batch/freeze.json'),runtimeSha:f.runtimeSha,opencode:'1.18.26',model:f.model,reasoning:f.variant,budgetSeconds:1800,slots:[{slot:1,instance_id:task.instance_id,arm:'P',status:'not_started',Q:null,T:null,D:null}],input,config:f.config,offlineConfig:get('development/native-task-offline/build.json'),authorHarness:false,calibrationSha256:hash(dev+'/calibration.json'),preflightSha256:hash(dev+'/preflight.json'),files:Object.fromEntries(Object.entries(f.files).map(([p,h])=>[p.startsWith(process.cwd()+'/')?p.slice(process.cwd().length+1):path.basename(p),h])),realProviderRequestsBeforeFreeze:0,priorLocalExecutionAbsent:true,priorPausesUnchanged:true});
console.log('Frozen. A local commit and freeze-commit.json are required before dispatch.');
