import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {DatabaseSync} from 'node:sqlite';
import {adapterFor} from '/workspace/packages/connector/lib/readers.mjs';
import {adapterFor as oldAdapter} from '/baseline/packages/connector/lib/readers.mjs';
import {normalizeAdapterDiagnostics} from '/workspace/packages/connector/lib/diagnostics.mjs';
const root=await fs.mkdtemp(path.join(os.tmpdir(),'delivery-contract-')),rows=[];
const range={rangeStart:'2026-07-15',rangeEnd:'2026-08-14'},reload=x=>JSON.parse(JSON.stringify(x)),totals=r=>r.entries.map(e=>[e.date,e.totalTokens]);
const sourceId='11111111-1111-4111-8111-111111111111',agentAccountId='22222222-2222-4222-8222-222222222222';
const specs=[['antigravity','capture.jsonl',(id,d,i=10,o=5)=>({id,date:d,usage:{input_tokens:i,output_tokens:o,total_tokens:i+o}})],['claude_code','session.jsonl',(id,d,i=10,o=5)=>({type:'assistant',timestamp:d+'T12:00:00Z',message:{role:'assistant',id,usage:{input_tokens:i,output_tokens:o}}})],['gemini_cli','session-usage.jsonl',(id,d,i=10,o=5)=>({type:'gemini',id,timestamp:d+'T12:00:00Z',usageMetadata:{input:i,output:o,total:i+o}})],['qwen_code','token-usage-session.jsonl',(id,d,i=10,o=5)=>({schemaVersion:1,id,timestamp:d+'T12:00:00Z',inputTokens:i,outputTokens:o,totalTokens:i+o,cachedTokens:0,thoughtsTokens:0})]];
async function observe(name,fn){try{rows.push({name,...await fn()});}catch(e){rows.push({name,error:e.message,diagnosticCode:e.diagnosticCode??null,status:'requires_fixture_and_contract_review'});}}
try{
 for(const [agent,name,record]of specs){
  await observe('bound-migration-'+agent,async()=>{const dir=path.join(root,'migration-'+agent);await fs.mkdir(dir);const file=path.join(dir,name),source={dataPath:dir,sourceId,agentAccountId,agentId:agent};await fs.writeFile(file,JSON.stringify(record('old','2026-08-10'))+'\n');const before=await oldAdapter(agent).collect(source,range,{});await fs.writeFile(file,JSON.stringify(record('new','2026-08-11'))+'\n');const after=await adapterFor(agent).collect(source,range,reload(before.nextState));return {before:totals(before),actual:totals(after),expected:[['2026-08-10','15'],['2026-08-11','15']],completeness:after.completeness};});
  if(!['claude_code','antigravity'].includes(agent))continue;
  await observe('unfinished-replay-'+agent,async()=>{const dir=path.join(root,'unfinished-'+agent);await fs.mkdir(dir);const file=path.join(dir,name),moved=path.join(dir,'moved-'+name),source={dataPath:dir},a=adapterFor(agent),line=JSON.stringify(record('old','2026-08-10'));await fs.writeFile(file,line+'\n');const before=await a.collect(source,range,{});await fs.unlink(file);await fs.writeFile(moved,line);const unfinished=await a.collect(source,range,reload(before.nextState));await fs.appendFile(moved,'\n'+JSON.stringify(record('new','2026-08-11',4,3))+'\n');const after=await a.collect(source,range,reload(unfinished.nextState));return {before:totals(before),unfinished:totals(unfinished),expectedUnfinished:[['2026-08-10','15']],after:totals(after),expectedAfter:[['2026-08-10','15'],['2026-08-11','7']],completeness:after.completeness};});
 }
 await observe('mixed-antigravity',async()=>{const dir=path.join(root,'mixed');await fs.mkdir(dir);await fs.writeFile(path.join(dir,'capture.jsonl'),[specs[0][2]('good','2026-08-10'),{id:'unsupported',date:'2026-08-10'}].map(JSON.stringify).join('\n')+'\n');const r=await adapterFor('antigravity').collect({dataPath:dir},range,{});return {actual:totals(r),expected:[['2026-08-10','15']],expectedCompleteness:'partial',completeness:r.completeness,diagnostics:r.diagnostics};});
 const file=path.join(root,'opencode.db'),db=new DatabaseSync(file);try{
  db.exec('CREATE TABLE message (id TEXT,time_created INTEGER,data TEXT)');const put=(id,i,o)=>db.prepare('INSERT INTO message VALUES (?,?,?)').run(id,Date.parse('2026-08-10T12:00:00Z'),JSON.stringify({role:'assistant',tokens:{input:i,output:o,total:i+o}})),a=adapterFor('opencode'),source={dataPath:file,sourceId,agentAccountId,agentId:'opencode'};
  await observe('mixed-opencode',async()=>{put('good',10,5);put('unsupported',-1,0);const r=await a.collect(source,range,{});return {actual:totals(r),expected:[['2026-08-10','15']],expectedCompleteness:'partial',completeness:r.completeness,diagnostics:r.diagnostics};});
  await observe('conflict-consumer',async()=>{db.exec('DELETE FROM message');put('accepted',10,5);const before=await a.collect(source,range,{});db.exec('DELETE FROM message');put('accepted',100,50);put('new',4,3);const r=await a.collect(source,range,reload(before.nextState));return {before:totals(before),actual:totals(r),expected:[['2026-08-10','22']],expectedCompleteness:'partial',completeness:r.completeness,diagnostics:r.diagnostics,consumerDiagnostics:normalizeAdapterDiagnostics(r.diagnostics)};});
 }finally{db.close();}
 await observe('privacy-hex-id',async()=>{const dir=path.join(root,'privacy');await fs.mkdir(dir);const id='0123456789abcdef'.repeat(4);await fs.writeFile(path.join(dir,'session.jsonl'),JSON.stringify(specs[1][2](id,'2026-08-10'))+'\n');const r=await adapterFor('claude_code').collect({dataPath:dir,sourceId,agentId:'claude_code'},range,{});return {actual:totals(r),expected:[['2026-08-10','15']],rawIdPersisted:JSON.stringify(reload(r.nextState)).includes(id),expectedRawIdPersisted:false};});
 await observe('account-remap',async()=>{const file=path.join(root,'switch.jsonl');await fs.writeFile(file,JSON.stringify(specs[0][2]('same','2026-08-10'))+'\n');const source={dataPath:file,sourceId,agentAccountId,agentId:'antigravity',collectionMethod:'antigravity_cli_capture'},a=adapterFor('antigravity'),before=await a.collect(source,range,{}),after=await a.collect({...source,agentAccountId:'33333333-3333-4333-8333-333333333333'},range,reload(before.nextState));return {before:totals(before),actual:totals(after),expected:[['2026-08-10','15']],completeness:after.completeness};});
}finally{await fs.rm(root,{recursive:true,force:true});}
console.log(JSON.stringify({observations:rows},null,2));
