import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
const d='development/ledger-review-delivery',read=p=>JSON.parse(fs.readFileSync(p)),sha=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex'),f=read(d+'/manifest.json');
for(const [file,hash]of Object.entries(f.files))assert.equal(sha(file),hash,file);
assert.equal(execFileSync('git',['show','4eab8635:'+d+'/manifest.json']).toString(),fs.readFileSync(d+'/manifest.json','utf8'));
for(const entry of fs.readdirSync(d)){const p=path.join(d,entry);if(entry.endsWith('.json'))read(p);if(entry.endsWith('.mjs'))execFileSync(process.execPath,['--check',p]);if(entry.endsWith('.patch'))continue;assert.ok(!/Bearer [a-zA-Z0-9_-]{20}|sk-[a-zA-Z0-9_-]{24}|"(?:access_token|refresh_token|account_id)"\s*:|\/Users\/tahion/.test(fs.readFileSync(p,'utf8')),p);}
const r=read(d+'/result.json'),a=read(d+'/assessment.json'),delivery=read(d+'/delivery-receipt.json'),raw=read(d+'/raw-probes.json'),cost=read(d+'/costs.json'),receipts=read(d+'/recording-receipts.json');
assert.equal(r.Q,false);assert.equal(r.T,false);assert.equal(r.D,false);assert.equal(a.Q,false);assert.equal(a.T,false);assert.equal(a.D,false);assert.equal(r.stages.R,'not_started');assert.equal(r.stages.F,'not_started');assert.equal(r.realRetries,0);assert.equal(delivery.nativeCompleted,true);assert.equal(delivery.integrity.integrity.actualTreeVerified,true);assert.equal(sha(d+'/D0.patch'),delivery.patchSha256);assert.equal(sha(d+'/M.partial.patch'),delivery.patchSha256);
assert.equal(raw.suites.reduce((n,s)=>n+s.cases.length,0),23);assert.equal(raw.suites.flatMap(s=>s.cases).filter(x=>x.status==='pass').length,15);assert.equal(receipts.requests.length,76);
for(const key of ['input_tokens','output_tokens','cached_tokens','reasoning_tokens'])assert.equal(receipts.requests.reduce((n,r)=>n+r.usage[key],0),cost.real.usage[key]);assert.ok(cost.real.usage.cached_tokens<=cost.real.usage.input_tokens);assert.ok(cost.real.usage.reasoning_tokens<=cost.real.usage.output_tokens);
const selected=read(d+'/selected-observations.json');assert.equal(selected.correctedRetention.exitCode,0);assert.ok(selected.firstRetentionAttempt.seconds+selected.correctedRetention.seconds<180);assert.equal(selected.correctedRetention.observations.find(x=>x.case==='after-bound-delete').acceptedUsageRetained,false);
await import('./verify-code.mjs');
fs.writeFileSync(d+'/final-verification.json',JSON.stringify({passed:true,frozenManifestUnchanged:true,frozenFilesVerified:Object.keys(f.files).length,syntax:true,safePublicationScan:true,rawProbeArithmetic:true,usageArithmetic:true,patchHashes:true,actualDeliveryRecovery:true,sharedSchedulerAndRequestPolicyUnchanged:true,modelRequests:0,ciClaim:false},null,2)+'\n');console.log('PASS: frozen runtime/input files, syntax, publication boundary, 23 probes, usage and partial-delivery accounting');
