// Immutable nine-slot admission manifest. No auth or provider access.
import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
const root=path.resolve(process.argv[2]),sha=b=>createHash('sha256').update(b).digest('hex'),read=p=>JSON.parse(fs.readFileSync(p));
if(fs.existsSync(root+'/freeze.json'))throw Error('Never replace frozen inputs');
for(const name of ['final-H','final-R','final-default']){const r=read(root+'/'+name+'-result.json');if(!r.passed||r.realProviderRequests!==0||r.results.some(r=>!r.nativeCompleted||!r.termination.terminationVerified))throw Error('Missing installed candidate preflight');}
const calibration=read(root+'/calibration.json');if(calibration.realProviderRequests!==0||calibration.results.length!==12||calibration.results.some(r=>r.label.startsWith('wrong')?r.exit===0:r.exit!==0))throw Error('Missing independent calibration');
function manifest(root){const out={};function walk(d,p=''){for(const e of fs.readdirSync(d,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){if(e.name==='.git')continue;const file=d+'/'+e.name,n=p+e.name,s=fs.lstatSync(file);if(s.isDirectory())walk(file,n+'/');else if(s.isSymbolicLink()){const link=fs.readlinkSync(file);if(path.isAbsolute(link)||!path.resolve(path.dirname(file),link).startsWith(root+path.sep))throw Error('External input link');out[n]={symlink:link};}else if(s.isFile())out[n]={sha256:sha(fs.readFileSync(file)),executable:!!(s.mode&0o111)};else throw Error('Unsupported entry');}}walk(root);return out;}
const runtimeSha=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),bundle=root+'/bundle';
for(const n of fs.readdirSync(bundle).filter(n=>n.endsWith('.mjs')))if(!execFileSync('git',['show',runtimeSha+':lib/'+n]).equals(fs.readFileSync(bundle+'/'+n)))throw Error('Uncommitted or stale runtime: '+n);
const attempts=[],inputManifests={},tasks=[['quick-lru-take',['P','R','H']],['denque-drain',['R','H','P']],['eventemitter-collect',['H','P','R']]];
for(const [task,order]of tasks){const source=root+'/inputs/'+task,m=manifest(source),project=read(source+'/package.json').name;for(const arm of order){attempts.push({slot:attempts.length+1,task,project,arm,source});inputManifests[task+'-'+arm]=m;}}
const files={};for(const n of ['development/native-task-ab/run-comparison.mjs','development/native-task-ab/native-run.mjs','development/native-task-ab/container-session.mjs','development/native-task-ab/container-relay.mjs','development/native-task-ab/capture-candidate.mjs','development/native-task-ab/extract-candidate.py','development/native-task-abc/native-run.mjs','development/native-task-utility/container/stop-workload.mjs',...fs.readdirSync('development/native-task-investigation').filter(n=>/\.(md|mjs)$/.test(n)).map(n=>'development/native-task-investigation/'+n),...tasks.map(([t])=>'development/native-task-investigation/tasks/'+t+'/TASK.md')])files[path.resolve(n)]=sha(fs.readFileSync(n));
const f={version:1,experimentKind:'targeted-integration',createdAt:new Date().toISOString(),runtimeSha,model:'openai/gpt-5.6-luna',variant:'high',budgetMs:900000,strategy:'direct',preflightPassed:true,streamLimit:'remaining-task-budget',connectionTimeoutMs:30000,toolchain:read('local/native-sensitivity/targeted-20260914/freeze.json').toolchain,template:bundle,dependencies:bundle,config:read(root+'/experiment-config.json'),attempts,inputManifests,files,runtimeManifests:{[bundle]:manifest(bundle)}};
fs.writeFileSync(root+'/freeze.json',JSON.stringify(f),{flag:'wx'});
fs.writeFileSync('development/native-task-investigation/frozen-inputs.json',JSON.stringify({createdAt:f.createdAt,runtimeSha,freezeSha256:sha(fs.readFileSync(root+'/freeze.json')),model:f.model,effort:f.variant,taskDeadlineMs:f.budgetMs,diagnosticTaskMs:180000,order:attempts.map(a=>({slot:a.slot,task:a.task,arm:a.arm})),inputs:tasks.map(([task])=>({task,manifestSha256:sha(JSON.stringify(inputManifests[task+'-P'])),promptSha256:sha(fs.readFileSync(root+'/inputs/'+task+'/TASK.md'))})),realProviderRequestsBeforeFreeze:0},null,2)+'\n');
console.log(JSON.stringify({frozen:true,runtimeSha,attempts:9,realProviderRequests:0}));
