import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';
const root=path.resolve('local/native-type-compat-offline-subscribe/batch'),f=JSON.parse(fs.readFileSync(root+'/freeze.json')),read=p=>JSON.parse(fs.readFileSync(p)),hash=b=>createHash('sha256').update(b).digest('hex'),rows=[];
for(const a of f.attempts){const d=root+'/runs/'+a.task+'-'+a.arm;if(!fs.existsSync(d)){rows.push({...a,source:undefined,status:'not_started',Q:null,T:null,D:null,requests:0,knownUsage:null,unknownUsage:'not applicable: no request'});continue;}
 const requests=read(d+'/provider-metadata.json'),r=fs.existsSync(d+'/result.json')?read(d+'/result.json'):null,e=fs.existsSync(d+'/native-evidence.json')?read(d+'/native-evidence.json'):null;
 const knownUsage={input_tokens:0,output_tokens:0,total_tokens:0,cached_tokens:0,reasoning_tokens:0};for(const q of requests.filter(q=>q.forwarded&&q.usage))for(const k of Object.keys(knownUsage))knownUsage[k]+=q.usage[k]??0;
 const artifacts=d+'/candidate/.git/harness-task',entries=fs.existsSync(artifacts)?fs.readdirSync(artifacts):[],art=entries.length===1?artifacts+'/'+entries[0]:null,c=art&&fs.existsSync(art+'/type-compat.json')?read(art+'/type-compat.json'):null;
 const requestFiles=fs.readdirSync(d).filter(n=>/^request-\d+\.json$/.test(n));const diagnostics=[];
 for(const run of c?.runs??[]){const receipt=requestFiles.filter(n=>read(d+'/'+n).input?.some(x=>x.type==='function_call_output'&&x.call_id===run.callID&&JSON.stringify(x.output).includes(run.snapshot))).sort((a,b)=>+a.match(/\d+/)[0]-+b.match(/\d+/)[0]);diagnostics.push({status:run.status,reason:run.reason,callID:run.callID,snapshot:run.snapshot,baselineSnapshot:run.baselineSnapshot,surfaceHash:run.surfaceHash,delivered:run.delivered,receipt:receipt.length?{file:receipt[0],sha256:hash(fs.readFileSync(d+'/'+receipt[0]))}:null,cost:run.cost,process:run.process,consumers:run.consumers?.map(x=>({id:x.id,status:x.status,route:x.route,text:x.text,diagnostics:x.diagnostics}))});}
 rows.push({slot:a.slot,task:a.task,arm:a.arm,status:'executed',executionElapsedMs:r?.executionElapsedMs,cleanupElapsedMs:r?.cleanupElapsedMs,requests:requests.filter(x=>x.forwarded).length,workRequests:requests.filter(x=>x.forwarded&&x.requestKind==='work').length,titleRequests:requests.filter(x=>x.forwarded&&x.requestKind==='title').length,nativeTools:e?.tools.length,knownUsage,requestsWithoutUsage:requests.filter(x=>x.forwarded&&!x.usage).length,unknownServerOutcomes:requests.filter(x=>x.forwarded&&!x.terminalResponse&&x.serverCompletion!=='known_refusal').length,internalStatus:r?.workflowStatus,nativeCompleted:r?.nativeCompleted,stop:read(d+'/stop-verification.json'),compiler:c?{status:c.status,reason:c.reason,current:c.current,finalLimitation:c.finalLimitation,spentMs:c.spentMs,baselinePreparationMs:c.baselinePreparationMs,captureCost:c.captureCost,runs:diagnostics}:null,requestsEvidence:requests.map(x=>({index:x.requestIndex,kind:x.requestKind,model:x.model,effort:x.effort,status:x.status,serverCompletion:x.serverCompletion,usage:x.usage,responseId:x.responseId,requestSha256:fs.existsSync(d+'/request-'+x.requestIndex+'.json')?hash(fs.readFileSync(d+'/request-'+x.requestIndex+'.json')):null,responseSha256:fs.existsSync(d+'/response-'+x.requestIndex+'.sse')?hash(fs.readFileSync(d+'/response-'+x.requestIndex+'.sse')):null}))});
}
fs.writeFileSync(root+'/accounting.json',JSON.stringify({rows,tokenAccounting:'cache/reasoning are included subsets, not additional totals; null/missing usage is unknown',monetaryCost:null},null,2));console.log(JSON.stringify(rows.map(({requestsEvidence,compiler,...r})=>({...r,compiler:compiler?{status:compiler.status,analyses:compiler.runs.length,spentMs:compiler.spentMs,current:compiler.current}:null})),null,2));
