import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import {manifest} from '../native-task-integrated/run.mjs';
const root=path.resolve('local/native-type-compat-offline-subscribe/batch'),dev=path.resolve('development/native-type-compat-offline-subscribe'),original=path.resolve('development/native-type-compat-comparison');
const read=p=>JSON.parse(fs.readFileSync(p)),hash=b=>createHash('sha256').update(b).digest('hex');assert.ok(!fs.existsSync(root+'/freeze.json'));
const preflight=read(root+'/preflight.json'),audit=read(root+'/preflight-audit.json'),calibration=read(root+'/verified-calibration.json');assert.ok(preflight.passed&&audit.passed&&calibration.passed);assert.equal(calibration.results.length,7);
const runtimeSha='e18db1fe10223db52dcc05b3e769bca140367c2b',template=root+'/bundle',files={},add=f=>files[path.resolve(f)]=hash(fs.readFileSync(f));
for(const n of fs.readdirSync(template).filter(n=>n.endsWith('.mjs'))){assert.ok(execFileSync('git',['show',runtimeSha+':lib/'+n]).equals(fs.readFileSync(template+'/'+n)),n);add(template+'/'+n);}
assert.ok(execFileSync('git',['show',runtimeSha+':profiles/native/core.md']).equals(fs.readFileSync(template+'/core.md')));add(template+'/core.md');add(template+'/opencode.json');
assert.equal(read(template+'/node_modules/typescript/package.json').version,'6.0.3');
assert.equal(hash(fs.readFileSync(template+'/node_modules/typescript/lib/typescript.js')),'569177652966bd528c319171c7dd22860dbf72bde116cbc4f644f1d02bb12e39');
for(const n of ['typescript.js','tsc.js','_tsc.js'])add(template+'/node_modules/typescript/lib/'+n);
const attempts=['OFF','ON'].map((arm,i)=>({slot:i+1,task:'A',arm,project:'primus/eventemitter3',source:root+'/inputs/A'}));
const inputManifests={};for(const a of attempts)inputManifests['A-'+a.arm]=manifest(a.source);
const inventories=[];
for(const arm of ['OFF','ON']){const d=root+'/preflight/runs/A-'+arm;const e=read(d+'/native-evidence.json');assert.equal(e.sessions.length,2);assert.equal(e.sessions.filter(s=>s.parent_id===null).length,1);
 for(const n of fs.readdirSync(d).filter(n=>/^request-\d+\.json$/.test(n))){const r=read(d+'/'+n);if(!r.tools?.length)continue;const names=r.tools.map(t=>t.name);assert.ok(!names.includes('webfetch'));for(const name of ['read','apply_patch','bash','glob','grep'])assert.ok(names.includes(name));inventories.push({arm,request:n,role:JSON.stringify(r).includes('Implement the complete original task')?'author':'parent',tools:names,toolResults:r.input.filter(x=>x.type==='function_call_output').length,sha256:hash(fs.readFileSync(d+'/'+n))});}
 const nodes=e.tools.filter(t=>t.data.tool==='bash'&&t.data.state.input.command==='/usr/local/bin/node --version');assert.equal(nodes[0].data.state.output.trim(),'v24.19.0');
}
for(const n of fs.readdirSync(dev).filter(n=>/\.(mjs|md)$/.test(n)))add(dev+'/'+n);
for(const n of ['tasks/A.md','evaluation/A.cjs','evaluation/A.types.ts','evaluation/legacy.types.ts'])add(original+'/'+n);
for(const label of ['reference','alternative','missing','erased-types','legacy-break','runtime-break'])for(const n of ['index.js','index.d.ts','test/test.js','test/test.mjs','api.types.ts','README.md'])add(path.resolve('local/native-type-compat-comparison/batch/calibration/A',label,n));
for(const n of ['development/native-task-ab/run-comparison.mjs','development/native-task-abc/native-run.mjs','development/native-task-integrated/container-session.mjs','development/native-task-integrated/container-relay.mjs','development/native-task-ab/capture-candidate.mjs','development/native-task-ab/extract-candidate.py','development/native-task-utility/container/stop-workload.mjs','development/native-task-offline/build.json'])add(n);
for(const n of ['experiment-config.json','sources.json','verified-calibration.json','preflight.json','preflight-audit.json'])add(root+'/'+n);
const toolchain=path.resolve('../verified-change-harness/local/template-toolchain-20260908');add(toolchain+'/package/bin/opencode');
assert.equal(execFileSync('docker',['ps','--format','{{.Names}}'],{encoding:'utf8'}).trim(),'');
const f={version:1,experimentKind:'subscribe-offline',createdAt:new Date().toISOString(),runtimeSha,model:'openai/gpt-5.6-luna',variant:'high',budgetMs:1800000,strategy:'direct',preflightPassed:true,streamLimit:'remaining-task-budget',connectionTimeoutMs:30000,toolchain,template,dependencies:template,config:read(root+'/experiment-config.json'),attempts,inputManifests,files};
fs.writeFileSync(root+'/freeze.json',JSON.stringify(f),{flag:'wx',mode:0o600});
const record={createdAt:f.createdAt,runtimeSha,freezeSha256:hash(fs.readFileSync(root+'/freeze.json')),model:f.model,effort:f.variant,budgetMs:f.budgetMs,node:'v24.19.0',typescript:'6.0.3',image:'sha256:0ed6cee0b095ecf1e1e780418cb373d462f1b99643bb86db0a8de7dd58fc83a6',config:f.config,offlineOverride:read('development/native-task-offline/build.json'),order:attempts.map(({source,...a})=>a),sourceCommit:'b0144e940ace8add8f335a8adfbed9284eb419f3',originalTaskSha256:hash(fs.readFileSync(original+'/tasks/A.md')),actualPromptSha256:hash(fs.readFileSync(root+'/inputs/A/TASK.md')),environmentBlock:fs.readFileSync(root+'/inputs/A/TASK.md','utf8').slice(fs.readFileSync(original+'/tasks/A.md','utf8').length),inputManifestSha256:hash(JSON.stringify(inputManifests['A-OFF'])),preflight,audit,calibration,inventories,coverageControl:{reference:'required project regression clauses and documentation reviewed',withoutAddedRegressions:'rejected: missing explicitly requested author regression coverage'},realProviderRequestsBeforeFreeze:0,hashes:Object.fromEntries(Object.entries(files).map(([p,h])=>[path.relative(process.cwd(),p),h]))};
fs.writeFileSync(dev+'/frozen-inputs.json',JSON.stringify(record,null,2)+'\n',{flag:'wx'});console.log('Frozen exactly A/OFF then A/ON; 0 real provider requests so far.');
