import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import {manifest} from '../native-task-integrated/run.mjs';
const root=path.resolve('local/native-type-compat-comparison/batch'),dev=path.resolve('development/native-type-compat-comparison'),read=p=>JSON.parse(fs.readFileSync(p)),hash=b=>createHash('sha256').update(b).digest('hex');assert.ok(!fs.existsSync(root+'/freeze.json'));
const preflight=read(root+'/preflight.json'),audit=read(root+'/preflight-audit.json'),calibration=read(root+'/verified-calibration.json');assert.ok(preflight.passed&&audit.passed&&calibration.passed);assert.equal(calibration.results.length,14);
const runtimeSha='8264ce42ef198580af834dcb09df996ac1274f1d',template=root+'/bundle';
for(const n of fs.readdirSync(template).filter(n=>n.endsWith('.mjs')))assert.ok(execFileSync('git',['show',runtimeSha+':lib/'+n]).equals(fs.readFileSync(template+'/'+n)),n);
assert.ok(execFileSync('git',['show',runtimeSha+':profiles/native/core.md']).equals(fs.readFileSync(template+'/core.md')));
const attempts=[['A','OFF'],['A','ON'],['B','ON'],['B','OFF']].map(([task,arm],i)=>({slot:i+1,task,arm,project:'primus/eventemitter3',source:root+'/inputs/'+task}));
const runtimeManifests={},inputManifests={};for(const d of [template,...new Set(attempts.map(a=>a.source))])runtimeManifests[d]=manifest(d);for(const a of attempts)inputManifests[a.task+'-'+a.arm]=runtimeManifests[a.source];
const files={},add=f=>files[path.resolve(f)]=hash(fs.readFileSync(f));
function visit(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){if(['node_modules','.git'].includes(e.name))continue;const p=path.join(d,e.name);if(e.isDirectory())visit(p);else add(p);}}
visit(dev);for(const d of ['calibration/A','waitfor-calibration/B'])visit(root+'/'+d);
for(const n of ['development/native-task-ab/run-comparison.mjs','development/native-task-abc/native-run.mjs','development/native-task-integrated/container-session.mjs','development/native-task-integrated/container-relay.mjs','development/native-task-ab/capture-candidate.mjs','development/native-task-ab/extract-candidate.py','development/native-task-utility/container/stop-workload.mjs'])add(n);
for(const n of ['experiment-config.json','sources.json','verified-calibration.json','preflight.json','preflight-audit.json'])add(root+'/'+n);
const toolchain=path.resolve('../verified-change-harness/local/template-toolchain-20260908');add(toolchain+'/package/bin/opencode');
const containers=execFileSync('docker',['ps','-a','--format','{{.Names}}'],{encoding:'utf8'}).trim().split('\n').filter(n=>n.startsWith('template-dev-'));assert.deepEqual(containers,[]);
const f={version:1,experimentKind:'type-compat',createdAt:new Date().toISOString(),runtimeSha,model:'openai/gpt-5.6-luna',variant:'high',budgetMs:1800000,strategy:'direct',preflightPassed:true,streamLimit:'remaining-task-budget',connectionTimeoutMs:30000,toolchain,template,dependencies:template,config:read(root+'/experiment-config.json'),attempts,inputManifests,runtimeManifests,files};
fs.writeFileSync(root+'/freeze.json',JSON.stringify(f),{flag:'wx',mode:0o600});
fs.writeFileSync(dev+'/frozen-inputs.json',JSON.stringify({createdAt:f.createdAt,runtimeSha,freezeSha256:hash(fs.readFileSync(root+'/freeze.json')),model:f.model,effort:f.variant,budgetMs:f.budgetMs,config:f.config,order:attempts.map(({source,...a})=>a),inputs:['A','B'].map(task=>({task,project:'primus/eventemitter3',sourceCommit:'b0144e940ace8add8f335a8adfbed9284eb419f3',promptSha256:hash(fs.readFileSync(root+'/inputs/'+task+'/TASK.md')),inputManifestSha256:hash(JSON.stringify(runtimeManifests[root+'/inputs/'+task]))})),calibration,preflight,audit,realProviderRequestsBeforeFreeze:0,files:Object.fromEntries(Object.entries(files).filter(([p])=>p.includes('/development/')).map(([p,h])=>[path.relative(process.cwd(),p),h]))},null,2),{flag:'wx'});
console.log('Frozen four task-runs; no provider calls yet');
