import fs from 'node:fs';import path from 'node:path';import {createHash}from 'node:crypto';import {execFileSync}from 'node:child_process';
const root=path.resolve('local/native-task-ab/transfer'),primary=path.resolve('local/native-task-ab');const hash=b=>createHash('sha256').update(b).digest('hex');
function manifest(dir){const out={};const visit=(d,p='')=>{for(const e of fs.readdirSync(d,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){if(e.name==='.git')continue;const file=path.join(d,e.name),rel=p+e.name,st=fs.lstatSync(file);if(st.isSymbolicLink()){const target=fs.readlinkSync(file);if(path.isAbsolute(target)||!path.resolve(path.dirname(file),target).startsWith(dir+'/'))throw Error('Uncontained link');out[rel]={symlink:target};}else if(st.isDirectory())visit(file,rel+'/');else if(st.isFile())out[rel]={sha256:hash(fs.readFileSync(file)),executable:!!(st.mode&0o111)};else throw Error('Unsupported entry');}};visit(dir);return out;}
const gate=JSON.parse(fs.readFileSync(primary+'/transfer-gate.json'));if(gate.selected!=='H11'||gate.seriousUnresolvedCandidateRegression!==false)throw Error('Gate not established');if(JSON.parse(fs.readFileSync(primary+'/outcome.json')).status!=='finished')throw Error('Primary not finished');
const tasks=[{id:'promise-clear-queue',project:'p-debounce',commit:'792115ea04019c720ddc8753010c758c55796f77',order:['P','H11','H11','P']},{id:'throttle-callback-receivers',project:'p-throttle',commit:'09f6e9503dd590b9a3c9e33711ff65a23cf1032b',order:['H11','P','P','H11']}];
const attempts=[],inputManifests={},files={},sourceSummary=[];const pin=file=>files[path.resolve(file)]=hash(fs.readFileSync(file));
for(const t of tasks){const source=root+'/inputs/'+t.id;if(fs.readFileSync(source+'/TASK.md','utf8')!==fs.readFileSync('development/native-task-ab/transfer/tasks/'+t.id+'/TASK.md','utf8'))throw Error('Task mismatch');const actual=execFileSync('git',['-C',primary+'/transfer-sources/'+t.project,'rev-parse','HEAD'],{encoding:'utf8'}).trim();if(actual!==t.commit)throw Error('Source revision changed');
 const baseline=root+'/baseline-authorized/'+t.id+'/result.json';if(JSON.parse(fs.readFileSync(baseline)).exit!==0)throw Error('Baseline unavailable');pin(baseline);
 const calibration=root+'/calibration-authorized/'+t.id+'/results.json',rows=JSON.parse(fs.readFileSync(calibration));if(rows.length!==(t.id==='promise-clear-queue'?7:6)||rows.some(r=>!r.matched))throw Error('Calibration incomplete');pin(calibration);
 const m=manifest(source);sourceSummary.push({id:t.id,project:t.project,commit:t.commit,files:Object.keys(m).length,inputManifestSha256:hash(JSON.stringify(m)),installedLockSha256:hash(fs.readFileSync(source+'/node_modules/.package-lock.json'))});
 for(const [i,arm]of t.order.entries()){attempts.push({slot:attempts.length+1,task:t.id,project:t.project,repetition:Math.floor(i/2)+1,arm,source});inputManifests[t.id+'-'+arm]=m;}
 for(const variant of ['reference','alternative']){const location=root+'/'+(t.id==='throttle-callback-receivers'&&variant==='alternative'?'full-controls-v3':'full-controls-v2')+'/'+t.id+'/'+variant;const result=JSON.parse(fs.readFileSync(location+'/result.json'));if(result.exit!==0&&!(t.id==='throttle-callback-receivers'&&variant==='alternative'))throw Error('Unexpected full-control failure');pin(location+'/result.json');pin(location+'/files.json');}
}
const final=JSON.parse(fs.readFileSync(root+'/final-control-independent/results.json'));if(final.length!==4||final.some(r=>r.exit!==0))throw Error('Final controls failed');pin(root+'/final-control-independent/results.json');
for(const variant of ['baseline','alternative']){const file=root+'/timing-diagnostic/'+variant+'/result.json';if(JSON.parse(fs.readFileSync(file)).exit!==0)throw Error('Timing diagnosis changed');pin(file);}
for(const file of execFileSync('rg',['--files','lib','agents','development/native-task-ab','development/native-task-utility/container'],{encoding:'utf8'}).trim().split('\n').filter(x=>!x.startsWith('development/native-task-ab/results/')&&!x.endsWith('FREEZE.json')))pin(file);
for(const file of ['package.json','package-lock.json','docs/native-task/PROJECT-FEEDBACK.md','development/native-task-abc/native-run.mjs'])pin(file);
for(const file of [primary+'/transfer-gate.json',primary+'/corrected-diagnostic-verification.json',root+'/preparation-incidents.json',root+'/scheduler-verification.txt',root+'/primary-scheduler-regression.txt'])pin(file);
for(const [name,dir]of [['template',primary+'/bundle-corrected'],['dependencies',primary+'/plain-dependencies']]){const m=manifest(dir);fs.writeFileSync(root+'/'+name+'-manifest.json',JSON.stringify(m));pin(root+'/'+name+'-manifest.json');for(const [n,v]of Object.entries(m))if(!n.startsWith('node_modules/')&&v.sha256)pin(dir+'/'+n);}
const f={version:1,experimentKind:'transfer',selectedH:'H11',transferGatePassed:true,createdAt:new Date().toISOString(),head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),model:'openai/gpt-5.6-luna',variant:'high',budgetMs:900000,strategy:'direct',preflightPassed:true,toolchain:path.resolve('../verified-change-harness/local/template-toolchain-20260908'),template:primary+'/bundle-corrected',dependencies:primary+'/plain-dependencies',config:JSON.parse(fs.readFileSync(primary+'/experiment-config.json')),attempts,inputManifests,files};fs.writeFileSync(root+'/freeze.json',JSON.stringify(f),{flag:'wx'});
const publicFreeze={...f,template:'corrected materialized native-task bundle',dependencies:'same pinned plain native dependency bundle as primary',toolchain:'same Node24.19/OpenCode1.18.26/container image as primary',config:undefined,inputManifests:undefined,files:Object.fromEntries(Object.entries(files).map(([file,sha])=>[path.relative(process.cwd(),file),sha])),attempts:attempts.map(({source,...a})=>a),sources:sourceSummary,freezeSha256:hash(fs.readFileSync(root+'/freeze.json')),note:'Eight conditional runs only. Primary candidate unchanged. Known full-control timing failure disclosed in RUBRIC.md; no thresholds modified.'};fs.writeFileSync('development/native-task-ab/transfer/FREEZE.json',JSON.stringify(publicFreeze,null,2)+'\n',{flag:'wx'});console.log({frozen:true,slots:8,freezeSha256:publicFreeze.freezeSha256,head:f.head});
