import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';
import {runComparison} from '../../native-task-ab/run-comparison.mjs';import {stopWorkload} from '../../native-task-utility/container/stop-workload.mjs';import {startContainer,captureCandidate} from './session.mjs';import {resolveNativeResult} from '../../ledger-review-delivery/resolve-native-result.mjs';import {compactTaskResult} from '../../../lib/native-task-plugin.mjs';
const root=path.resolve('local/investigation-inspect-full-task/preflight');fs.mkdirSync(root,{mode:0o700});const get=f=>JSON.parse(fs.readFileSync(f)),f=get('local/investigation-inspect-full-task/prepared.json');fs.writeFileSync(root+'/freeze.json',JSON.stringify(f));
const task=fs.readFileSync(f.attempts[0].source+'/TASK.md','utf8');let seq=0,parent=0,author=0,authorTaskSeen=false;const responses=[];
const result=await runComparison({root,startContainer,captureCandidate,stopWorkload,readAuth:()=>({access:'scripted-no-auth',accountId:'fixture'}),fetchImpl:async(url,options)=>{
 assert.equal(url,'https://chatgpt.com/backend-api/codex/responses');const body=JSON.parse(options.body),all=JSON.stringify(body),names=(body.tools??[]).map(t=>t.name),isAuthor=all.includes('Implement the complete original task');let call;
 if(names.length&&!isAuthor&&parent++===0)call={name:'harness_task',args:{}};
 if(isAuthor){assert.ok(all.includes(JSON.stringify(task).slice(1,-1)));assert.ok(names.includes('harness_investigate'));authorTaskSeen=true;call=[{name:'read',args:{filePath:'TASK.md'}},{name:'bash',args:{command:'git diff --check',description:'Check full clean baseline',timeout:10000}}][author++];}
 const id='preflight_'+(++seq),item=call?{id:'fc_'+seq,type:'function_call',call_id:'call_'+seq,name:call.name,arguments:JSON.stringify(call.args),status:'completed'}:{id:'msg_'+seq,type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:'Scripted transport preflight complete; no implementation attempted.',annotations:[]}]};
 const base={id,object:'response',created_at:1,model:body.model,status:'in_progress',output:[]},events=[{type:'response.created',response:base},{type:'response.output_item.added',output_index:0,item:call?{...item,arguments:'',status:'in_progress'}:{...item,status:'in_progress',content:[]}}];
 if(call)events.push({type:'response.function_call_arguments.delta',item_id:item.id,output_index:0,delta:item.arguments});else events.push({type:'response.content_part.added',item_id:item.id,output_index:0,content_index:0,part:{type:'output_text',text:'',annotations:[]}},{type:'response.output_text.delta',item_id:item.id,output_index:0,content_index:0,delta:item.content[0].text});
 events.push({type:'response.output_item.done',output_index:0,item},{type:'response.completed',response:{...base,status:'completed',output:[item],usage:{input_tokens:1,output_tokens:1,total_tokens:2}}});const bytes=Buffer.from(events.map(e=>'data: '+JSON.stringify(e)+'\n\n').join(''));responses.push(bytes);return new Response(bytes,{status:200,headers:{'content-type':'text/event-stream'}});
}});
assert.equal(result.status,'finished',JSON.stringify(result));assert.ok(authorTaskSeen);const out=root+'/runs/account-switch-ledger-I1',stop=get(out+'/stop-verification.json');assert.ok(stop.terminationVerified&&stop.captureSaved&&stop.relayRemoved);assert.equal(get(out+'/input-verification.json').files,259);assert.equal(get(out+'/recording-config.json').bounds.totalBytes,1073741824);
const rec=get(out+'/provider-metadata.json');assert.equal(rec.length,seq);for(const r of rec){assert.ok(r.recording.evidenceComplete);assert.ok(fs.readFileSync(out+'/response-'+r.requestIndex+'.sse').equals(responses[r.requestIndex-1]));}
assert.ok(fs.existsSync(out+'/native-result-full.json'));const native=get(out+'/native-evidence.json'),capture=get(out+'/patch-capture.json'),full=get(out+'/native-result-full.json'),run=get(out+'/native-result-resolution.json').run;
// Exact existing resolver on an isolated compact-result control; no new native session.
const control=root+'/resolver-control';fs.mkdirSync(control);fs.cpSync(out+'/task-artifacts/'+run,control+'/'+run,{recursive:true});full.remaining=Array(1000).fill('Synthetic large result detail for resolver only');const receipt=compactTaskResult(full,{artifacts:full.artifacts,executionDirectory:full.executionDirectory,sessions:full.sessions});assert.ok(receipt.detailOmitted);native.tools.find(t=>t.data.tool==='harness_task').data.state.output=JSON.stringify(receipt);fs.writeFileSync(control+'/'+run+'/result.json',JSON.stringify(full));const resolved=resolveNativeResult({native,artifactRoot:control,capture});assert.ok(resolved.proof.compact);assert.deepEqual(resolved.workflow.remaining,full.remaining);
const absent=spawnSync('docker',['inspect',get(out+'/session/container.json').name],{encoding:'utf8'});assert.notEqual(absent.status,0);assert.match(absent.stderr,/no such object/i);
const summary={passed:true,fullTaskSeen:true,inventoryFiles:259,profile:get(out+'/recording-config.json'),normalStop:stop,capture:true,resolverDetailOmitted:true,scriptedRequests:seq,realProviderRequests:0,investigatorStarts:0};fs.writeFileSync('development/investigation-direct-ledger-pair/inspect-full-task/preflight.json',JSON.stringify(summary,null,2)+'\n');console.log(JSON.stringify({passed:true,scriptedRequests:seq,realProviderRequests:0}));
