import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import {pathToFileURL} from 'node:url';
import {manifest as tree} from '../../native-task-integrated/run.mjs';
import {image} from '../../native-task-integrated/container-session.mjs';
import {inspectFullTaskRecordingProfile as profile} from '../../native-task-ab/provider-recording.mjs';
const dev='development/investigation-followup/full-task',root=path.resolve('local/investigation-followup-full-task');
const sha=b=>createHash('sha256').update(b).digest('hex'),hash=f=>sha(fs.readFileSync(f));
const save=(f,o)=>fs.writeFileSync(f,JSON.stringify(o,null,2)+'\n',{flag:'wx',mode:0o600});
const runtimeSha='d59a527d120e4cd256ded6d8270154fbbcff5d36',old='development/plain-ledger-native-high';
const archive=path.resolve('local/plain-ledger-native-high/baseline.tar');
assert.equal(hash(archive),'ea549fcc30d8facef77af8ebebc280910a24537e44ad8c6cfcbdc4888b5dcab1');
const task=fs.readFileSync(old+'/original-task.txt'),environment=fs.readFileSync(old+'/environment.txt');
assert.equal(sha(task),'c855e75f5b4705f703f5c4c39e01d05c73505854c32a4ff97dd5d564e82573eb');assert.equal(sha(environment),'aa0afe37ca2ec1f3564642a02842d71472b72b88225069be22a4cbbe8fb114cc');
fs.mkdirSync(root,{mode:0o700});const candidate=root+'/candidate',source=root+'/source',bundle=root+'/bundle';fs.mkdirSync(candidate);fs.mkdirSync(source);
execFileSync('git',['archive','--format=tar','--output='+root+'/candidate.tar',runtimeSha]);execFileSync('tar',['-xf',root+'/candidate.tar','-C',candidate]);
const {materializeNativeTemplate}=await import(pathToFileURL(candidate+'/lib/native-template.mjs'));materializeNativeTemplate({repositoryRoot:candidate,outputDirectory:bundle,task:true});
for(const n of ['node_modules','package-lock.json','rg'])fs.cpSync('local/native-task-integrated/plain-dependencies/'+n,bundle+'/'+n,{recursive:true,verbatimSymlinks:true});
const cfg=JSON.parse(fs.readFileSync(bundle+'/opencode.json'));cfg.instructions=['/template/core.md'];cfg.plugin=['file:///template/native-task-plugin.mjs'];fs.writeFileSync(bundle+'/opencode.json',JSON.stringify(cfg));
for(const n of fs.readdirSync(bundle).filter(n=>n.endsWith('.mjs')))assert.equal(hash(bundle+'/'+n),hash(candidate+'/lib/'+n));
execFileSync('tar',['-xf',archive,'-C',source]);assert.ok(!fs.existsSync(source+'/.git'));fs.writeFileSync(source+'/TASK.md',Buffer.concat([task,environment]),{flag:'wx'});
const input=tree(source);assert.equal(Object.keys(input).length,259);
const config=JSON.parse(fs.readFileSync('local/native-investigation-ledger-pair/experiment-config.json'));config.permission={...config.permission,external_directory:{'*':'deny'},webfetch:'deny'};config.agent={build:{permission:{webfetch:'deny'}}};
const f={version:1,experimentKind:'investigation-followup-full-task',runtimeSha,candidateSha:runtimeSha,image,model:'openai/gpt-5.6-luna',variant:'high',budgetMs:3600000,strategy:'direct',preflightPassed:true,streamLimit:'remaining-task-budget',connectionTimeoutMs:30000,recordingProfile:profile.name,recordingBounds:profile,toolchain:path.resolve('../verified-change-harness/local/template-toolchain-20260908'),template:bundle,dependencies:bundle,config,attempts:[{slot:1,task:'account-switch-ledger',arm:'I1',project:'Tah10n/viberacing',source}],inputManifests:{'account-switch-ledger-I1':input},runtimeManifests:{[bundle]:tree(bundle)},files:{}};
save(root+'/prepared.json',f);
const space=fs.statfsSync(root);save(root+'/storage-preflight.json',{availableBytes:space.bavail*space.bsize,recordingBytes:profile.totalBytes,nativeOutputReserveBytes:268435456,recoveryReserveBytes:1610612736,requiredBytes:profile.totalBytes+268435456+1610612736,passed:space.bavail*space.bsize>profile.totalBytes+268435456+1610612736});assert.ok(space.bavail*space.bsize>profile.totalBytes+268435456+1610612736);
console.log(JSON.stringify({prepared:true,root,files:Object.keys(input).length,promptSha256:hash(source+'/TASK.md'),profile}));
