import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
const local=path.resolve('local/direct-assertion-review-model-pair'),dev='development/direct-assertion-review/model-pair',prior='development/plain-ledger-native-high';
const get=p=>JSON.parse(fs.readFileSync(p)),hash=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex'),save=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n',{flag:'wx'});
const check=get(local+'/preflight-verified/verification.json');assert.equal(check.passed,true);
const evidence=[];for(const arm of ['AR0','AR1']){
 const d=local+'/preflight-verified/runs/account-switch-ledger-'+arm,stop=get(d+'/stop-verification.json'),r=get(d+'/result.json');assert.ok(stop.terminationVerified&&stop.captureSaved&&stop.relayRemoved&&stop.forwardingClosed&&!stop.activeProviderHandlers);
 const native=get(d+'/native-evidence.json'),author=JSON.parse(native.tools.find(t=>t.data.tool==='harness_task').data.state.output).sessions.author;
 const requestFiles=fs.readdirSync(d).filter(n=>/^request-\d+\.json$/.test(n));let initial;
 for(const n of requestFiles.sort((a,b)=>Number(a.match(/\d+/)[0])-Number(b.match(/\d+/)[0]))){const body=get(d+'/'+n);const texts=(body.input??[]).flatMap(x=>Array.isArray(x.content)?x.content.map(c=>c.text??''):[x.content??'']);const t=texts.find(t=>t.includes('Implement the complete original task below'));if(t){initial=t;break;}}
 assert.ok(initial?.includes(fs.readFileSync(dev+'/TASK.md','utf8').trim()));assert.equal(initial.includes('During self-review,'),arm==='AR1');
 evidence.push({arm,scriptedRequests:r.requests,authorSession:author,delivery:r.delivery,stop,initialRequestFullTask:true,correctInstruction:true,patchSha256:hash(d+'/model.patch'),patchEqualsNativeTerminal:true,outputManifestSha256:hash(d+'/native-output/manifest.json'),rawResultSha256:hash(d+'/result.json')});
}
save(dev+'/preflight.json',{...check,evidence,scriptedRequests:18,realProviderRequests:0,preparationFailures:[{directory:'preflight',reason:'Scripted fixture expected edit but Luna inventory provides apply_patch'},{directory:'preflight-final',reason:'Observer read executionDirectory from internal report instead of native receipt'}]});
const f=get(local+'/prepared.json');f.experimentKind='assertion-review-pair';f.controlsPassed=true;f.authorIsolationPassed=true;
const files=[...fs.readdirSync(dev).map(n=>dev+'/'+n),...fs.readdirSync(prior).filter(n=>/\.(mjs|json|md|txt|patch|py)$/.test(n)).map(n=>prior+'/'+n),
'development/native-task-ab/run-comparison.mjs','development/native-task-abc/native-run.mjs','development/native-task-integrated/container-session.mjs','development/native-task-integrated/container-relay.mjs','development/native-task-utility/container/stop-workload.mjs','development/polybench-pilot/capture.mjs','development/native-output-retention/output-files.mjs','development/native-task-ab/extract-candidate.py','development/native-task-offline/build.json',f.toolchain+'/package/bin/opencode'];
for(const file of files)f.files[path.resolve(file)]=hash(file);
for(const campaign of ['polybench-pilot','preservation-nudge-revision-2-model-pair'])for(const name of ['freeze.json','freeze-commit.json','scheduling-paused.json','outcome.json']){const p=path.resolve('local/'+campaign+'/batch/'+name);if(fs.existsSync(p))f.files[p]=hash(p);}
fs.mkdirSync(local+'/batch',{mode:0o700});save(local+'/batch/freeze.json',f);
save(dev+'/manifest.json',{version:1,stage:'frozen_before_model_requests',freezeSha256:hash(local+'/batch/freeze.json'),candidates:f.candidates,baseline:'2b16b6a8ad75b6b852adc5e2189e6d4a8d93eabd',reference:'9e389a6dbc1b0c9813599fb61eceb6958d8c4de4',image:f.image,resources:{cpus:2,memoryMb:3072,workMemoryMb:1536,pids:512},opencode:'1.18.26',node:'24.19.0',git:'2.39.5',model:f.model,reasoning:f.variant,budgetSeconds:1800,config:f.config,offlineConfig:get('development/native-task-offline/build.json'),flags:Object.fromEntries(['CONTEXT','CHECKS','TYPE_COMPAT','SENSITIVITY','INVESTIGATION','COMMAND_HINTS','PRESERVATION_NUDGE','EXTRA_ATTENTION'].map(k=>['HARNESS_TASK_'+k,0])),slots:f.attempts.map(({source,...a})=>({...a,status:'not_started'})),preparation:get(dev+'/preparation.json'),preflightSha256:hash(dev+'/preflight.json'),files:Object.fromEntries(Object.entries(f.files).map(([p,h])=>[p.startsWith(process.cwd()+'/')?p.slice(process.cwd().length+1):p,h])),realProviderRequestsBeforeFreeze:0});
console.log('Pair frozen; commit before dispatch.');
