import fs from 'node:fs';
import path from 'node:path';
import {materializeNativeTemplate} from '../../lib/native-template.mjs';
const root=path.resolve('local/investigation-followup/installed');
fs.mkdirSync(root,{recursive:true});
materializeNativeTemplate({repositoryRoot:process.cwd(),outputDirectory:root+'/bundle',task:true});
for(const n of ['node_modules','package-lock.json','rg'])fs.cpSync('local/native-task-integrated/plain-dependencies/'+n,root+'/bundle/'+n,{recursive:true,verbatimSymlinks:true});
const cfg=JSON.parse(fs.readFileSync(root+'/bundle/opencode.json'));cfg.instructions=['/template/core.md'];cfg.plugin=['file:///template/native-task-plugin.mjs'];fs.writeFileSync(root+'/bundle/opencode.json',JSON.stringify(cfg));
fs.copyFileSync('local/native-investigation-ledger-pair/experiment-config.json',root+'/experiment-config.json');
console.log(root);
