// Existing freeze schema, three preselected inputs; no provider requests.
import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
const root=path.resolve(process.argv[2]),pub=path.resolve('development/native-task-sensitivity/targeted-20260914'),read=p=>JSON.parse(fs.readFileSync(p)),sha=b=>createHash('sha256').update(b).digest('hex');
if(fs.existsSync(root+'/freeze.json'))throw Error('Never replace frozen inputs');
const prep=read(root+'/preparation.json'),fixture=read(root+'/installed-preflight.json');if(!fixture.passed||fixture.realProviderRequests!==0||!fixture.results.every(r=>r.nativeCompleted&&r.termination.terminationVerified))throw Error('Preflight missing');
function manifest(dir){const out={};function walk(d,p=''){for(const e of fs.readdirSync(d,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){if(e.name==='.git')continue;const f=path.join(d,e.name),n=p+e.name,s=fs.lstatSync(f);if(s.isDirectory())walk(f,n+'/');else if(s.isSymbolicLink()){const link=fs.readlinkSync(f);if(path.isAbsolute(link)||!path.resolve(path.dirname(f),link).startsWith(dir+path.sep))throw Error('External symlink');out[n]={symlink:link};}else if(s.isFile())out[n]={sha256:sha(fs.readFileSync(f)),executable:!!(s.mode&0o111)};else throw Error('Unsupported file');}}walk(dir);return out;}
const cases=[['case-a','denque-remove-where','Denque.prototype.removeWhere',7],['case-b','quick-lru-computed','QuickLRU.getOrInsertComputed',2],['case-c','denque-remove-where','Denque.prototype.removeWhere',6]],attempts=[],files={},inputManifests={},baseManifests={};
for(const [id,task,method,index] of cases){
 const source=root+'/inputs/'+id,seedPatch=root+'/admission/'+id+'/input.patch',checked=read(root+'/checks/'+id+'/result.json');if(checked.results.some(r=>r.exit!==0)||checked.baselineExit!==0||!checked.termination.terminationVerified)throw Error('Invalid input check');
 const report=read(root+'/admission/'+id+'/report.json'),selected=report.variants[index];if(selected.status!=='passed')throw Error('Not a survivor');
 const contract=fs.readFileSync('development/native-task-h00-transfer/tasks/'+task+'/TASK.md','utf8').trim();
 const prompt=fs.readFileSync(pub+'/TASK.template.md','utf8').replace('{{CONTRACT}}',contract).replace('{{METHOD}}',method).replace('{{DIFF}}',selected.diff);
 fs.writeFileSync(source+'/TASK.md',prompt);fs.mkdirSync(pub+'/inputs/'+id,{recursive:true});fs.writeFileSync(pub+'/inputs/'+id+'/TASK.md',prompt);fs.copyFileSync(seedPatch,pub+'/inputs/'+id+'/input.patch');fs.writeFileSync(pub+'/inputs/'+id+'/variant.diff',selected.diff+'\n');
 const base=manifest(source);baseManifests[id]=base;
 // A private scratch tree is excluded from all author mounts.
 const copy=root+'/freeze-check-'+id;fs.cpSync(source,copy,{recursive:true,verbatimSymlinks:true,filter:f=>!path.relative(source,f).split(path.sep).includes('node_modules')});execFileSync('git',['init','-q'],{cwd:copy});execFileSync('git',['apply','--check',seedPatch],{cwd:copy});execFileSync('git',['apply',seedPatch],{cwd:copy});inputManifests[id+'-H1']={...Object.fromEntries(Object.entries(base).filter(([n])=>n.startsWith('node_modules/'))),...manifest(copy)};
 const row={slot:attempts.length+1,task:id,originalTask:task,project:id==='case-b'?'quick-lru':'denque',arm:'H1',source,seedPatch,seedSha256:sha(fs.readFileSync(seedPatch))};attempts.push(row);files[seedPatch]=row.seedSha256;files[source+'/TASK.md']=sha(prompt);
}
const bundle=root+'/bundle';for(const n of fs.readdirSync(bundle).filter(n=>n.endsWith('.mjs')))if(!execFileSync('git',['show',prep.runtimeSha+':lib/'+n]).equals(fs.readFileSync(bundle+'/'+n)))throw Error('Runtime changed: '+n);
for(const n of ['development/native-task-sensitivity/run.mjs','development/native-task-ab/run-comparison.mjs','development/native-task-ab/native-run.mjs','development/native-task-ab/container-session.mjs','development/native-task-ab/container-relay.mjs','development/native-task-ab/capture-candidate.mjs','development/native-task-ab/extract-candidate.py','development/native-task-abc/native-run.mjs','development/native-task-utility/container/stop-workload.mjs',...fs.readdirSync(pub).filter(n=>n.endsWith('.mjs')||n.endsWith('.md')).map(n=>path.relative(process.cwd(),pub)+'/'+n)])files[path.resolve(n)]=sha(fs.readFileSync(n));
const freeze={version:1,experimentKind:'sensitivity-targeted',createdAt:new Date().toISOString(),runtimeSha:prep.runtimeSha,executionHarnessSha:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),model:'openai/gpt-5.6-luna',variant:'high',budgetMs:900000,strategy:'direct',preflightPassed:true,streamLimit:'remaining-task-budget',connectionTimeoutMs:30000,toolchain:prep.toolchain,template:bundle,dependencies:bundle,config:read(root+'/experiment-config.json'),attempts,inputManifests,baseManifests,files,runtimeManifests:{[bundle]:manifest(bundle)}};
fs.writeFileSync(root+'/freeze.json',JSON.stringify(freeze),{flag:'wx'});
fs.writeFileSync(pub+'/frozen-inputs.json',JSON.stringify({createdAt:freeze.createdAt,runtimeSha:prep.runtimeSha,freezeSha256:sha(fs.readFileSync(root+'/freeze.json')),model:freeze.model,effort:freeze.variant,taskDeadlineMs:900000,diagnosticBudgetMs:180000,order:attempts.map(a=>a.task),inputs:attempts.map(a=>({case:a.task,project:a.project,seedSha256:a.seedSha256,promptSha256:files[a.source+'/TASK.md'],baseManifestSha256:sha(JSON.stringify(baseManifests[a.task])),patchedManifestSha256:sha(JSON.stringify(inputManifests[a.task+'-H1']))})),realProviderRequestsBeforeFreeze:0},null,2)+'\n');
console.log(JSON.stringify({frozen:true,attempts:3,runtimeSha:prep.runtimeSha,realProviderRequests:0}));
