// Public summaries in the existing attempts/results/costs layout. Raw streams stay local.
import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';
const root=path.resolve(process.argv[2]),pub=path.resolve('development/native-task-sensitivity/targeted-20260914'),read=p=>JSON.parse(fs.readFileSync(p)),sha=b=>createHash('sha256').update(b).digest('hex'),sum=(xs,key)=>xs.reduce((n,x)=>n+(Number.isFinite(x[key])?x[key]:0),0);
const freeze=read(root+'/freeze.json'),outcome=read(root+'/outcome.json'),assessment=read(pub+'/assessment.json');if(!['finished','paused'].includes(outcome.status))throw Error('Series must stop');
fs.mkdirSync(pub+'/attempts',{recursive:true});fs.mkdirSync(pub+'/patches',{recursive:true});const rows=[];
for(const a of freeze.attempts){
 const dir=root+'/runs/'+a.task+'-'+a.arm;if(!fs.existsSync(dir))continue;
 const r=read(dir+'/result.json'),stop=read(dir+'/stop-verification.json'),native=read(dir+'/native-evidence.json'),metadata=read(dir+'/provider-metadata.json');
 if(!stop.terminationVerified||!stop.relayRemoved||stop.activeProviderHandlers!==0)throw Error('Unverified stop');
 const taskRoot=dir+'/candidate/.git/harness-task',ids=fs.readdirSync(taskRoot).filter(n=>fs.existsSync(taskRoot+'/'+n+'/worktree'));if(ids.length!==1)throw Error('Expected one author');const artifacts=taskRoot+'/'+ids[0];
 const workflow=read(artifacts+'/result.json'),events=read(artifacts+'/tool-events.json'),sense=fs.existsSync(artifacts+'/sensitivity-events.json')?read(artifacts+'/sensitivity-events.json'):[];
 const requests=fs.readdirSync(dir).filter(n=>/^request-\d+\.json$/.test(n)).map(n=>read(dir+'/'+n)),authorRequests=requests.filter(j=>(j.input??[]).some(x=>x.role==='user'&&JSON.stringify(x.content).includes('Implement the complete original task')));
 const forwarded=metadata.filter(m=>m.forwarded),usages=forwarded.filter(m=>m.usage).map(m=>m.usage),usage={providerRequests:forwarded.length,requestsWithoutUsage:forwarded.filter(m=>!m.usage).length,inputTokens:sum(usages,'input_tokens'),outputTokens:sum(usages,'output_tokens'),totalTokens:sum(usages,'total_tokens'),cachedInputTokens:sum(usages,'cached_tokens'),reasoningTokens:sum(usages,'reasoning_tokens'),cachedSubsetUnknownRequests:forwarded.filter(m=>!Number.isFinite(m.usage?.cached_tokens)).length,reasoningSubsetUnknownRequests:forwarded.filter(m=>!Number.isFinite(m.usage?.reasoning_tokens)).length};
 const diagnostics=sense.map(e=>{const d=JSON.parse(e.output);return {callID:e.callID,originalArguments:e.originalArguments,selectedVariant:d.selectedVariant??null,snapshot:d.snapshot,tests:d.tests,command:d.command,status:d.status,engineExecuted:d.engineExecuted,baseline:d.baseline,sourceState:e.sourceState,stale:e.stale,elapsedMs:e.elapsedMs,taskDiagnosticMs:e.taskDiagnosticMs,cost:d.cost,terminationVerified:d.terminationVerified,variants:d.variants.map(m=>({ref:m.ref,file:m.fileName,operator:m.mutatorName,diff:m.diff,status:m.status,exit:m.exit,output:m.output}))};});
 const verifyDir=root+'/checks/'+a.task+'-'+a.arm,verification=read(verifyDir+'/verification.json'),patch=fs.readFileSync(verifyDir+'/verified.patch'),patchFile='patches/'+a.task+'-terminal.patch';fs.writeFileSync(pub+'/'+patchFile,patch);
 const authorSummary=fs.existsSync(artifacts+'/implementation-original.json')?read(artifacts+'/implementation-original.json').parts.filter(p=>p.type==='text').map(p=>p.text).join('\n'):null;
 const timeline=events.map((e,i)=>({index:i+1,callID:e.callID,tool:e.tool,state:e.state,exit:e.exit??null,startedAt:e.startedAt,completedAt:e.completedAt,changedState:e.before!==e.after,action:(e.args?.command??e.args?.filePath??e.args?.path??(e.tool==='apply_patch'?'apply project patch':'')).replaceAll(/\/work\/repo\/\.git\/harness-task\/[^/]+\/worktree/g,'<task-worktree>').slice(0,300)}));
 const row={slot:a.slot,case:a.task,project:a.project,runtimeSha:freeze.runtimeSha,advertisedInAllAuthorRequests:authorRequests.length>0&&authorRequests.every(j=>j.tools.some(t=>t.name==='harness_sense')),authorRequests:authorRequests.length,diagnosticCalls:diagnostics.length,replayCalls:diagnostics.filter(d=>d.selectedVariant).length,diagnostics,timeline,authorSummary,patch:patchFile,patchSha256:sha(patch),nativeCompleted:r.nativeCompleted,nativeExit:r.exitCode,stopReason:r.stopReason,phaseCount:r.phaseCount,nativeSessions:native.sessions.length,authorSessions:native.sessions.filter(s=>s.parent_id).length,toolCalls:native.tools.length,workflowStatus:r.workflowStatus,capturedWorkflowStatus:workflow.status,workflowRepairs:r.repairs,completedCommands:workflow.completedCommands,termination:stop,usage,executionElapsedMs:r.executionElapsedMs,cleanupElapsedMs:r.cleanupElapsedMs,preparationAndCaptureElapsedMs:Date.parse(read(dir+'/completed.json').at)-Date.parse(read(dir+'/started.json').at)-r.elapsedMs,ordinary:verification.ordinary,independent:verification.independent,offlineSensitivity:verification.offline,changedFromSeed:verification.changedFromSeed,terminalApplicable:verification.terminalApplicable,assessment:assessment[a.task]};
 fs.writeFileSync(pub+'/attempts/'+a.task+'.json',JSON.stringify(row,null,2)+'\n');fs.writeFileSync(pub+'/attempts/'+a.task+'-requests.json',JSON.stringify(metadata.map(m=>({requestIndex:m.requestIndex,requestKind:m.requestKind,forwarded:m.forwarded,status:m.status??null,forwardedAt:m.forwardedAt,finishedAt:m.finishedAt,usage:m.usage??null,serverCompletion:m.serverCompletion??null,error:m.error??null,requestSha256:fs.existsSync(dir+'/request-'+m.requestIndex+'.json')?sha(fs.readFileSync(dir+'/request-'+m.requestIndex+'.json')):null})),null,2)+'\n');rows.push(row);
}
const totals={attempts:rows.length,S:rows.filter(r=>r.assessment.S).length,T:rows.filter(r=>r.assessment.T).length,correctCompleted:rows.filter(r=>r.assessment.S&&r.assessment.T).length,providerRequests:sum(rows.map(r=>r.usage),'providerRequests'),unknownUsageRequests:sum(rows.map(r=>r.usage),'requestsWithoutUsage'),inputTokens:sum(rows.map(r=>r.usage),'inputTokens'),outputTokens:sum(rows.map(r=>r.usage),'outputTokens'),totalTokens:sum(rows.map(r=>r.usage),'totalTokens'),cachedInputTokens:sum(rows.map(r=>r.usage),'cachedInputTokens'),reasoningTokens:sum(rows.map(r=>r.usage),'reasoningTokens'),toolCalls:sum(rows,'toolCalls'),diagnosticCalls:sum(rows,'diagnosticCalls'),replayCalls:sum(rows,'replayCalls'),executionElapsedMs:sum(rows,'executionElapsedMs'),cleanupElapsedMs:sum(rows,'cleanupElapsedMs'),preparationAndCaptureElapsedMs:sum(rows,'preparationAndCaptureElapsedMs')};
const diagnostics=rows.flatMap(r=>r.diagnostics.map(d=>d.cost));const costs={modelRuns:totals,authorDiagnostics:Object.fromEntries(['commands','engineMs','preparationMs','commandMs','totalMs'].map(k=>[k,sum(diagnostics,k)])),offlineVerification:rows.map(r=>({case:r.case,ordinaryMs:r.ordinary.elapsedMs,independentMs:r.independent.elapsedMs,sensitivity:r.offlineSensitivity.cost})),preparationAdmission:['case-2','case-a','case-b','case-c'].map(id=>({case:id,cost:read(root+'/admission/'+id+'/report.json').cost})),preparationWallMs:Date.parse(read(root+'/launch-admission.json').at)-Date.parse(read(root+'/preparation.json').startedAt),containerPreflightMs:read(root+'/installed-preflight.json').results[0].elapsedMs,monetaryCost:null,accounting:'Cache/reasoning are subsets. Author diagnostics are inside native time. Preparation/evaluator are separate model-free work. Developing Codex usage is recorded separately; unknown fields remain unknown.'};
const prep=read(pub+'/preparation.json');
costs.transportFixtures={realProviderRequests:0,scriptedUpstreamRequests:sum(prep.transportScenarios,'upstreamRequests'),scenarios:prep.transportScenarios.length,installed:[]};
for(const mode of fs.readdirSync(root+'/transport').filter(n=>n.startsWith('installed-'))){const runs=root+'/transport/'+mode+'/runs';for(const n of fs.readdirSync(runs)){const r=read(runs+'/'+n+'/result.json');costs.transportFixtures.installed.push({mode,slot:r.slot,elapsedMs:r.elapsedMs,nativeCompleted:r.nativeCompleted,terminationVerified:r.termination?.terminationVerified});}}
costs.containerPreflightScriptedRequests=read(root+'/installed-preflight.json').results[0].requests.length;
costs.preparationAndAdmissionStartedAt=read(root+'/preparation.json').startedAt;
costs.inputCheckCommands=freeze.attempts.map(a=>({case:a.task,ordinary:read(root+'/checks/'+a.task+'/result.json').results,evaluatorExecutions:2,realProviderRequests:0}));
costs.bFailureReproduction={ordinaryCommands:1,sensitivity:read(root+'/b-baseline-reproduction/result.json').report.cost,realProviderRequests:0,elapsedMsFromArtifactTimestamps:Math.round(fs.statSync(root+'/b-baseline-reproduction/result.json').mtimeMs-fs.statSync(root+'/b-baseline-reproduction/session/container.json').mtimeMs),timingNote:'Artifact timestamp span; not an independently instrumented timer.'};
fs.writeFileSync(pub+'/costs.json',JSON.stringify(costs,null,2)+'\n');fs.writeFileSync(pub+'/results.json',JSON.stringify({kind:'three-targeted-development-tasks',outcome,runtimeSha:freeze.runtimeSha,model:freeze.model,effort:freeze.variant,taskDeadlineMs:900000,diagnosticBudgetMs:180000,totals,rows:rows.map(({timeline,diagnostics,authorSummary,offlineSensitivity,...r})=>r),replacements:0,additionalRealSmokes:0,historicalResultsUnchanged:true,liftEstablished:false},null,2)+'\n');console.log(JSON.stringify(totals));
