import fs from 'node:fs';import path from 'node:path';import {projectCheck} from '../native-task-ab/project-check.mjs';import {runtimeControl} from './control-patches.mjs';import {script} from './evaluation-cases.mjs';
const root=path.resolve(process.argv[2]??'local/native-task-h00-transfer'),outputName=process.argv[3]??'calibration';const tasks=JSON.parse(fs.readFileSync('development/native-task-h00-transfer/tasks.json'));
export const changes={
 'denque-rotate':[['wrong-direction','((steps % n) + n) % n','((-steps % n) + n) % n'],['no-validation',"if (typeof steps !== 'number' || !isFinite(steps) || Math.floor(steps) !== steps) throw new Error('Invalid rotation');",''],['lost-capacity','  this._head = 0;\n  this._fromArray(rotated);','  this._capacity = undefined;\n  this._head = 0;\n  this._fromArray(rotated);']],
 'denque-remove-where':[['wrong-index','predicate(values[i], i)','predicate(values[i], 0)'],['reversed-survivors','this._fromArray(retained);','this._fromArray(retained.reverse());'],['eager-mutation','var values = this.toArray();\n  var retained','var values = this.toArray(); this.clear();\n  var retained']],
 'eventemitter-prepend':[['appends',"prepend ? 'unshift' : 'push'","'push'"],['once-is-persistent','return addListener(this, event, fn, context, true, true);','return addListener(this, event, fn, context, false, true);'],['loses-context','return addListener(this, event, fn, context, false, true);','return addListener(this, event, fn, undefined, false, true);']],
 'eventemitter-remove-context':[['removes-other-context','listeners[i].context === context','listeners[i].context !== context'],['wrong-count','return removed;','return removed ? 1 : 0;'],['misses-symbols','var names = this.eventNames(),','var names = this.eventNames().filter(function (name) { return typeof name === "string"; }),']],
 'fastq-running-tasks':[['includes-queued','return active.map(function (item) { return item.value })','return active.map(function (item) { return item.value }).concat(getQueue())'],['retains-completed','active.splice(active.indexOf(token), 1)',''],['reverses-start-order','return active.map(function (item) { return item.value })','return active.map(function (item) { return item.value }).reverse()']],
 'fastq-on-idle':[['ignores-pending','if (self.idle()) return Promise.resolve()','if (self.running() === 0) return Promise.resolve()'],['overwrites-drain','idleWaiters.push(resolve)','self.drain = resolve; idleWaiters.push(resolve)'],['misses-kill-idle','    self.drain = noop\n    notifyIdle()','    self.drain = noop']],
 'quick-lru-computed':[['undefined-is-miss','if (this.has(key))','if (this.get(key) !== undefined)'],['no-recency','return this.get(key);','return this.peek(key);'],['factory-error-swallowed','const value = factory(key);','let value; try { value = factory(key); } catch { return undefined; }']],
 'quick-lru-prune':[['shadow-deleted','!this.#cache.has(key) && this.#deleteIfExpired(key, item)','this.#deleteIfExpired(key, item)'],['no-old-expiration','!this.#cache.has(key) && this.#deleteIfExpired(key, item)','false'],['wrong-count','return count;','return 0;']],
 'ufo-query-sort':[['ignores-option','if (options.sort) keys.sort();',''],['sorts-default','if (options.sort) keys.sort();','keys.sort();'],['consumer-not-threaded','stringifyQuery(mergedQuery, options)','stringifyQuery(mergedQuery)']],
 'ufo-append-query':[['replaces-values','merged[key] = ([] as any[]).concat(merged[key], Array.isArray(value) ? value : [value ?? ""]);','merged[key] = value;'],['drops-falsy','if (value === undefined ||','if (!value ||'],['pollution-unfiltered','if (key === "__proto__" || key === "constructor") continue;','']],
 'ms-format-unit':[['ignores-forced-unit','if (options?.unit !== undefined)','if (false && options?.unit !== undefined)'],['wrong-rounding','Math.round(ms / size)','Math.ceil(ms / size)'],['invalid-unit-falls-back',"if (!Object.prototype.hasOwnProperty.call(units, options.unit)) throw new Error('Unknown unit');","if (!Object.prototype.hasOwnProperty.call(units, options.unit)) return fmtShort(ms);"]],
 'ms-parse-compound':[['drops-global-sign','return negative ? -total : total;','return total;'],['accepts-no-separator',"count === 0 ? gap !== '' : !/^ +$/.test(gap)","count === 0 ? gap !== '' : !/^ *$/.test(gap)"],['accepts-trailing-garbage','if (!count || end !== input.length)','if (!count)']]
};
const build=t=>['ufo','ms'].includes(t.project)?'npm run build && ':'';
const reports=[];
for(const task of tasks.filter(t=>!process.env.TASK_FILTER||process.env.TASK_FILTER.split(',').includes(t.id))){
 const source=path.join(root,'inputs',task.id),reference=runtimeControl(task.id,source),variants=[['baseline',{}],['reference',reference],['alternative',runtimeControl(task.id,source,'alternative')]];
 for(const [name,before,after]of changes[task.id]){const overlay={...reference};const file=Object.keys(overlay).find(f=>overlay[f].includes(before));if(!file)throw Error('Mutation anchor missing: '+task.id+'/'+name);overlay[file]=overlay[file].replace(before,after);variants.push([name,overlay]);}
 for(const [name,runtime]of variants){
  const output=path.join(root,outputName,task.id,name);const overlay=Object.fromEntries(Object.entries({...runtime,'.h00-independent.cjs':script(task.id,task.project)}).map(([n,text])=>[n,Buffer.from(text).toString('base64')]));
  const result=await projectCheck({source,output,toolchain:path.resolve('../verified-change-harness/local/template-toolchain-20260908'),overlay,command:['sh','-c',build(task)+'timeout 10s node .h00-independent.cjs']});
  const expectedPass=['reference','alternative'].includes(name),row={task:task.id,variant:name,expectedPass,exit:result.exit,matched:(result.exit===0)===expectedPass,elapsedMs:result.elapsedMs};reports.push(row);fs.mkdirSync(path.join(root,outputName),{recursive:true});fs.writeFileSync(path.join(root,outputName,'results.json'),JSON.stringify(reports,null,2));console.log(JSON.stringify(row));
 }
}
if(reports.some(r=>!r.matched))process.exitCode=1;
