// Calibration controls are never mounted into an author container.
import fs from 'node:fs';import path from 'node:path';
export function runtimeControl(task,source,variant='reference'){
 const read=n=>fs.readFileSync(path.join(source,n),'utf8'),out={};let s,file;
 const alt=variant==='alternative';
 if(task.startsWith('denque-')){
  file='index.js';s=read(file);let code;
  if(task==='denque-rotate')code=`\nDenque.prototype.rotate = function rotate(steps) {\n  if (steps === undefined) steps = 1;\n  if (typeof steps !== 'number' || !isFinite(steps) || Math.floor(steps) !== steps) throw new Error('Invalid rotation');\n  var n = this.size();\n  if (n < 2) return this;\n  var k = ((steps % n) + n) % n;\n  var values = this.toArray();\n  ${alt?'var rotated = []; for (var i = 0; i < n; i++) rotated.push(values[(i + n - k) % n]);':'var rotated = values.slice(n - k).concat(values.slice(0, n - k));'}\n  this._head = 0;\n  this._fromArray(rotated);\n  return this;\n};\n`;
  else code=`\nDenque.prototype.removeWhere = function removeWhere(predicate) {\n  if (typeof predicate !== 'function') throw new Error('Invalid predicate');\n  var values = this.toArray();\n  ${alt?'var marks = values.map(function (value, index) { return !!predicate(value, index); }); var retained = values.filter(function (_, index) { return !marks[index]; });':'var retained = []; for (var i = 0; i < values.length; i++) if (!predicate(values[i], i)) retained.push(values[i]);'}\n  this._head = 0;\n  this._fromArray(retained);\n  return values.length - retained.length;\n};\n`;
  s+=code;
 }else if(task==='eventemitter-prepend'){
  file='index.js';s=read(file);
  if(!alt){s=s.replace('fn, context, once) {\n  if','fn, context, once, prepend) {\n  if').replace("else if (!emitter._events[evt].fn) emitter._events[evt].push(listener);", "else if (!emitter._events[evt].fn) emitter._events[evt][prepend ? 'unshift' : 'push'](listener);").replace('else emitter._events[evt] = [emitter._events[evt], listener];','else emitter._events[evt] = prepend ? [listener, emitter._events[evt]] : [emitter._events[evt], listener];');}
  for(const [method,once]of [['prependListener',false],['prependOnceListener',true]])s+=`\nEventEmitter.prototype.${method} = function (event, fn, context) {\n${alt?`  addListener(this, event, fn, context, ${once});\n  var evt = prefix ? prefix + event : event, list = this._events[evt];\n  if (!list.fn) list.unshift(list.pop());\n  return this;`:`  return addListener(this, event, fn, context, ${once}, true);`}\n};\n`;
 }else if(task==='eventemitter-remove-context'){
  file='index.js';s=read(file)+`\nEventEmitter.prototype.removeListenersByContext = function (context) {\n  var names = this.eventNames(), removed = 0;\n  for (var n = 0; n < names.length; n++) {\n    var evt = prefix ? prefix + names[n] : names[n], entry = this._events[evt];\n    var listeners = entry.fn ? [entry] : entry;\n    ${alt?`for (var i = 0; i < listeners.length; i++) {\n      if (listeners[i].context === context) { removed++; this.removeListener(names[n], listeners[i].fn, context, listeners[i].once); }\n    }`:`var keep = [];\n    for (var i = 0; i < listeners.length; i++) {\n      if (listeners[i].context === context) removed++; else keep.push(listeners[i]);\n    }\n    if (!keep.length) clearEvent(this, evt);\n    else this._events[evt] = keep.length === 1 ? keep[0] : keep;`}\n  }\n  return removed;\n};\n`;
 }else if(task==='fastq-running-tasks'){
  file='queue.js';s=read(file);s=s.replace('  var cache = reusify(Task)',`  var active = ${alt?'new Map()':'[]'}\n  var originalWorker = worker\n  worker = function (value, done) {\n    var token = { value: value }\n    ${alt?'active.set(token, value)':'active.push(token)'}\n    originalWorker.call(this, value, function (err, result) {\n      ${alt?'active.delete(token)':'active.splice(active.indexOf(token), 1)'}\n      done(err, result)\n    })\n  }\n\n  var cache = reusify(Task)`);s=s.replace('    running: running,',`    runningTasks: function () { return ${alt?'Array.from(active.values())':'active.map(function (item) { return item.value })'} },\n    running: running,`);
 }else if(task==='fastq-on-idle'){
  file='queue.js';s=read(file).replace('  var errorHandler = null','  var errorHandler = null\n  var idleWaiters = []');s=s.replace('    idle: idle,',`    onIdle: function () {\n      ${alt?'return new Promise(function (resolve) { if (self.idle()) resolve(); else idleWaiters.push(resolve) })':'if (self.idle()) return Promise.resolve()\n      return new Promise(function (resolve) { idleWaiters.push(resolve) })'}\n    },\n    idle: idle,`);
  s=s.replace('  function running () {',`  function notifyIdle () {\n    if (self.idle()) {\n      var waiting = idleWaiters\n      idleWaiters = []\n      for (var i = 0; i < waiting.length; i++) waiting[i]()\n    }\n  }\n\n  function running () {`);
  s=s.replace('      self.drain()\n    }\n  }','      self.drain()\n    }\n    notifyIdle()\n  }');s=s.replaceAll('    self.drain = noop\n  }','    self.drain = noop\n    notifyIdle()\n  }');
 }else if(task==='quick-lru-computed'){
  file='index.js';s=read(file).replace('\n\tget(key) {',`\n\tgetOrInsertComputed(key, factory) {\n\t\t${alt?'if (!this.has(key)) {\n\t\t\tconst value = factory(key);\n\t\t\tthis.set(key, value);\n\t\t\treturn value;\n\t\t}\n\n\t\treturn this.get(key);':'if (this.has(key)) {\n\t\t\treturn this.get(key);\n\t\t}\n\n\t\tconst value = factory(key);\n\t\tthis.set(key, value);\n\t\treturn value;'}\n\t}\n\n\tget(key) {`);
 }else if(task==='quick-lru-prune'){
  file='index.js';s=read(file).replace('\n\tget(key) {',`\n\tpruneExpired() {\n\t\tlet count = 0;\n\t\t${alt?'const visible = new Map([...this.#oldCache, ...this.#cache]);\n\t\tfor (const [key, item] of visible) {\n\t\t\tif (this.#deleteIfExpired(key, item)) {\n\t\t\t\tcount++;\n\t\t\t}\n\t\t}':'for (const [key, item] of this.#oldCache) {\n\t\t\tif (!this.#cache.has(key) && this.#deleteIfExpired(key, item)) {\n\t\t\t\tcount++;\n\t\t\t}\n\t\t}\n\n\t\tfor (const [key, item] of this.#cache) {\n\t\t\tif (this.#deleteIfExpired(key, item)) {\n\t\t\t\tcount++;\n\t\t\t}\n\t\t}'}\n\n\t\treturn count;\n\t}\n\n\tget(key) {`);
 }else if(task==='ufo-query-sort'){
  file='src/query.ts';s=read(file).replace('export function stringifyQuery(query: QueryObject): string {\n  return Object.keys(query)',`export interface StringifyQueryOptions {\n  sort?: boolean;\n}\n\nexport function stringifyQuery(query: QueryObject, options: StringifyQueryOptions = {}): string {\n  const keys = Object.keys(query);\n  if (options.sort) keys.sort(${alt?'(a, b) => a < b ? -1 : a > b ? 1 : 0':''});\n  return keys`);out[file]=s;
  file='src/utils.ts';s=read(file).replace('export function withQuery(input: string, query: QueryObject): string {','export function withQuery(input: string, query: QueryObject, options?: import("./query").StringifyQueryOptions): string {').replace('parsed.search = stringifyQuery(mergedQuery);','parsed.search = stringifyQuery(mergedQuery, options);');
 }else if(task==='ufo-append-query'){
  file='src/utils.ts';s=read(file)+`\n/** Append query values after existing values. */\nexport function appendQuery(input: string, query: QueryObject): string {\n  const parsed = parseURL(input);\n  const merged: QueryObject = parseQuery(parsed.search);\n  for (const key of Object.keys(query)) {\n    if (key === "__proto__" || key === "constructor") continue;\n    const value = query[key];\n    if (value === undefined || (Array.isArray(value) && value.length === 0)) continue;\n    ${alt?'const additions = Array.isArray(value) ? [...value] : [value ?? ""];\n    if (Object.prototype.hasOwnProperty.call(merged, key)) merged[key] = ([] as any[]).concat(merged[key], additions);\n    else merged[key] = value;':'if (Object.prototype.hasOwnProperty.call(merged, key)) {\n      merged[key] = ([] as any[]).concat(merged[key], Array.isArray(value) ? value : [value ?? ""]);\n    } else {\n      merged[key] = value;\n    }'}\n  }\n  parsed.search = stringifyQuery(merged);\n  return stringifyParsedURL(parsed);\n}\n`;
 }else if(task==='ms-format-unit'){
  file='src/index.ts';s=read(file).replace('interface Options {',"export interface Options {\n  unit?: 'ms' | 's' | 'm' | 'h' | 'd' | 'w' | 'mo' | 'y';");s=s.replace('  return options?.long ? fmtLong(ms) : fmtShort(ms);',`  if (options?.unit !== undefined) {\n    const units = {ms: [1, 'millisecond'], s: [s, 'second'], m: [m, 'minute'], h: [h, 'hour'], d: [d, 'day'], w: [w, 'week'], mo: [mo, 'month'], y: [y, 'year']} as const;\n    if (!Object.prototype.hasOwnProperty.call(units, options.unit)) throw new Error('Unknown unit');\n    const [size, name] = units[options.unit];\n    if (options.unit === 'ms') return options.long ? \`\${ms} ms\` : \`\${ms}ms\`;\n    ${alt?"const rounded = Math.round(ms / size);\n    return options.long ? `${rounded} ${name}${Math.abs(ms) >= size * 1.5 ? 's' : ''}` : `${rounded}${options.unit}`;":"return options.long ? plural(ms, Math.abs(ms), size, name) : `${Math.round(ms / size)}${options.unit}`;"}\n  }\n  return options?.long ? fmtLong(ms) : fmtShort(ms);`);
 }else if(task==='ms-parse-compound'){
  file='src/index.ts';s=read(file)+`\n/** Parse an explicitly unit-bearing duration sum. */\nexport function parseCompound(str: string): number {\n  if (typeof str !== 'string' || str.length === 0 || str.length > 100) {\n    throw new Error('Invalid duration input');\n  }\n  const negative = str[0] === '-';\n  const input = negative ? str.slice(1) : str;\n  const terms = /${alt?'(\\d*\\.?\\d+ *[a-z]+)':'(\\d*\\.?\\d+ *[a-z]+)'}/gi;\n  let total = 0;\n  let end = 0;\n  let count = 0;\n  for (const match of input.matchAll(terms)) {\n    const gap = input.slice(end, match.index);\n    if (count === 0 ? gap !== '' : !/^ +$/.test(gap)) return NaN;\n    const value = parse(match[0]);\n    if (Number.isNaN(value)) return NaN;\n    total += value;\n    count++;\n    end = match.index! + match[0].length;\n  }\n  if (!count || end !== input.length) return NaN;\n  return negative ? -total : total;\n}\n`;
  if(alt)s=read(file)+`\n/** Parse duration terms by consuming the input left-to-right. */\nexport function parseCompound(str: string): number {\n  if (typeof str !== 'string' || str.length === 0 || str.length > 100) throw new Error('Invalid duration input');\n  const negative = str.startsWith('-');\n  let rest = negative ? str.slice(1) : str;\n  let sum = 0;\n  while (rest.length > 0) {\n    const term = /^\\d*\\.?\\d+ *[a-z]+/i.exec(rest);\n    if (!term) return NaN;\n    const value = parse(term[0]);\n    if (Number.isNaN(value)) return NaN;\n    sum += value;\n    rest = rest.slice(term[0].length);\n    if (!rest) return negative ? -sum : sum;\n    const gap = /^ +/.exec(rest);\n    if (!gap) return NaN;\n    rest = rest.slice(gap[0].length);\n    if (!rest) return NaN;\n  }\n  return NaN;\n}\n`;
 }else throw Error('Unknown control task');
 out[file]=s;return out;
}
