import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
const root=path.resolve(process.argv[2]??'local/native-task-h00-transfer'),pub=path.resolve('development/native-task-h00-transfer');
const hash=b=>createHash('sha256').update(b).digest('hex');
function manifest(dir){const out={};function visit(d,prefix=''){for(const e of fs.readdirSync(d,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){if(e.name==='.git')continue;const file=path.join(d,e.name),name=prefix+e.name,st=fs.lstatSync(file);if(st.isSymbolicLink()){const target=fs.readlinkSync(file);if(path.isAbsolute(target)||!path.resolve(path.dirname(file),target).startsWith(dir+'/'))throw Error('Uncontained link: '+file);out[name]={symlink:target};}else if(st.isDirectory())visit(file,name+'/');else if(st.isFile())out[name]={sha256:hash(fs.readFileSync(file)),executable:!!(st.mode&0o111)};else throw Error('Unsupported file');}}visit(dir);return out;}
const tasks=JSON.parse(fs.readFileSync(pub+'/tasks.json')),schedule=JSON.parse(fs.readFileSync(pub+'/schedule.json'));if(tasks.length!==12||schedule.length!==48||schedule.some(r=>r.state!=='not_started'))throw Error('Invalid planned campaign');
const calibration=JSON.parse(fs.readFileSync(pub+'/calibration.json'));if(calibration.cases.length!==72||calibration.cases.some(r=>!r.matched)||calibration.completeControls.length!==24)throw Error('Calibration incomplete');
const controls=JSON.parse(fs.readFileSync(root+'/final-independent-v2/results.json'));if(controls.length!==24||controls.some(r=>r.independentExit!==0||!r.ordinaryPatchApplication||(r.types&&r.types.exit!==0)))throw Error('Portable controls incomplete');
const preflight=JSON.parse(fs.readFileSync(root+'/installed-preflight.json'));if(!preflight.passed||preflight.realProviderRequests!==0||preflight.results.length!==2||preflight.results.some(r=>!r.nativeCompleted||!r.termination.terminationVerified||r.elapsedMs<190000))throw Error('Real long-stream installed preflight incomplete');
const files={},pin=file=>files[path.resolve(file)]=hash(fs.readFileSync(file));
for(const relative of execFileSync('rg',['--files','development/native-task-h00-transfer','development/native-task-ab','development/native-task-utility/container'],{encoding:'utf8'}).trim().split('\n'))if(!relative.includes('/results/')&&!relative.endsWith('/FREEZE.json'))pin(relative);
for(const name of ['development/native-task-abc/native-run.mjs','lib/benchmark/statistics.mjs','package.json','package-lock.json'])pin(name);
for(const name of ['installed-preflight.json','installed-preflight-initial.json','restore-evidence.json','selected-controls.json','final-independent-v2/results.json','scheduler-final.txt','scheduler-primary-final.txt','scheduler-previous-final.txt','statistics-check.json'])pin(root+'/'+name);
const inputManifests={},sources=[];
for(const task of tasks){const source=root+'/inputs/'+task.id;if(fs.readFileSync(source+'/TASK.md','utf8')!==fs.readFileSync(task.taskFile,'utf8'))throw Error('Task changed');const m=manifest(source);if(Object.keys(m).some(n=>n.startsWith('.pnpm-store/')||n.includes('.h00-independent')||n.includes('h00-contract')))throw Error('Preparation data leaked into author input');inputManifests[task.id+'-P']=m;inputManifests[task.id+'-H00']=m;const file=root+'/input-manifests/'+task.id+'.json';fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(m),{flag:'wx'});pin(file);sources.push({...task,files:Object.keys(m).length,inputManifestSha256:hash(JSON.stringify(m))});}
for(const name of ['bundle','plain-dependencies']){const m=manifest(root+'/'+name),expected=JSON.parse(fs.readFileSync(root+'/'+name+'-manifest.json'));if(JSON.stringify(Object.keys(m).sort())!==JSON.stringify(Object.keys(expected).sort())||Object.entries(expected).some(([k,v])=>JSON.stringify(m[k])!==JSON.stringify(v)))throw Error('Restored installed bytes changed');pin(root+'/'+name+'-manifest.json');for(const [n,v]of Object.entries(m))if(v.sha256)pin(root+'/'+name+'/'+n);}
const attempts=schedule.map(({state,...r})=>({...r,source:root+'/inputs/'+r.task}));const f={version:1,experimentKind:'h00-transfer',createdAt:new Date().toISOString(),candidateCommit:'1cebebb082163250a0f78269acc164edfc3c6268',publicationBase:'e336b94b1511d232dac885960db9cda8cf5857d9',model:'openai/gpt-5.6-luna',variant:'high',budgetMs:900000,connectionTimeoutMs:30000,streamLimit:'remaining-task-budget',strategy:'direct',preflightPassed:true,toolchain:path.resolve('../verified-change-harness/local/template-toolchain-20260908'),template:root+'/bundle',dependencies:root+'/plain-dependencies',config:JSON.parse(fs.readFileSync(root+'/experiment-config.json')),attempts,inputManifests,files,runtimeManifests:{[root+'/bundle']:manifest(root+'/bundle'),[root+'/plain-dependencies']:manifest(root+'/plain-dependencies')}};
pin(f.toolchain+'/package/bin/opencode');
fs.writeFileSync(root+'/freeze.json',JSON.stringify(f),{flag:'wx',mode:0o600});
const summary={version:f.version,experimentKind:f.experimentKind,createdAt:f.createdAt,candidateCommit:f.candidateCommit,publicationBase:f.publicationBase,model:f.model,variant:f.variant,budgetMs:f.budgetMs,connectionTimeoutMs:f.connectionTimeoutMs,streamLimit:f.streamLimit,strategy:f.strategy,flags:{HARNESS_TASK_CONTEXT:0,HARNESS_TASK_CHECKS:0},freezeSha256:hash(fs.readFileSync(root+'/freeze.json')),realSmokes:0,plannedRuns:48,sources,attempts:schedule,analysis:'paired project-block percentile bootstrap, all 46656 block draws; equal task weights',preflight:{scriptedOnly:true,realDelayPerArmMs:190000,passed:true},fileHashes:Object.fromEntries(Object.entries(files).filter(([n])=>!n.includes('/local/')).map(([n,h])=>[path.relative(process.cwd(),n),h]))};fs.writeFileSync(pub+'/FREEZE.json',JSON.stringify(summary,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({frozen:true,slots:48,freezeSha256:summary.freezeSha256,realProviderRequests:0}));
