import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
import {manifest} from '../../native-task-integrated/run.mjs';
const root=path.resolve('local/native-type-compat-offline-subscribe/repeatability'),dev=path.resolve('development/native-type-compat-offline-subscribe/repeatability'),read=p=>JSON.parse(fs.readFileSync(p)),hash=b=>createHash('sha256').update(b).digest('hex');
assert.ok(!fs.existsSync(root+'/freeze.json'));const prep=read(root+'/preparation.json'),prior=read(dev+'/../frozen-inputs.json'),preflight=read(root+'/preflight.json'),audit=read(root+'/preflight-audit.json');assert.ok(preflight.passed&&audit.passed);
const containers=execFileSync('docker',['ps','--format','{{.Names}}'],{encoding:'utf8'}).trim().split('\n').filter(Boolean);assert.ok(!containers.some(n=>n.startsWith('template-dev-')),'Prior harness workload still alive');
const files={};for(const [p,h]of Object.entries(prep.verifiedPriorHashes)){assert.equal(hash(fs.readFileSync(p)),h,p);files[path.resolve(p)]=h;}
for(const p of ['development/native-task-ab/run-comparison.mjs',...fs.readdirSync(dev).map(n=>dev+'/'+n),root+'/preflight.json',root+'/preflight-audit.json'])files[path.resolve(p)]=hash(fs.readFileSync(p));
const previous=read('local/native-type-compat-offline-subscribe/batch/freeze.json'),template=fs.realpathSync(root+'/bundle'),source=root+'/inputs/A',input=manifest(source);assert.equal(hash(JSON.stringify(input)),prior.inputManifestSha256);
const attempts=prep.order.map(a=>({...a,source}));
const f={...previous,createdAt:new Date().toISOString(),repeatability:true,template,dependencies:template,attempts,files,inputManifests:{'A-OFF':input,'A-ON':input},runtimeManifests:{[source]:input,[template]:manifest(template)}};
fs.writeFileSync(root+'/freeze.json',JSON.stringify(f),{flag:'wx',mode:0o600});
const record={createdAt:f.createdAt,freezeSha256:hash(fs.readFileSync(root+'/freeze.json')),runtimeSha:f.runtimeSha,order:prep.order,model:f.model,effort:f.variant,budgetMs:f.budgetMs,actualPromptSha256:prior.actualPromptSha256,inputManifestSha256:prior.inputManifestSha256,config:f.config,offlineOverride:prior.offlineOverride,node:prior.node,typescript:prior.typescript,image:prior.image,preflight,audit,unrelatedContainersPreserved:containers,realProviderRequestsBeforeFreeze:0,files:Object.fromEntries(Object.entries(files).map(([p,h])=>[path.relative(process.cwd(),p),h])),runtimeManifestHashes:Object.fromEntries(Object.entries(f.runtimeManifests).map(([p,m])=>[path.relative(process.cwd(),p),hash(JSON.stringify(m))]))};
fs.writeFileSync(dev+'/frozen-inputs.json',JSON.stringify(record,null,2)+'\n',{flag:'wx'});console.log('Four-slot freeze complete; no live harness containers.');
