import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {createPreservationNudge,mochaReport} from '../../lib/native-preservation-nudge.mjs';
const extraction=spawnSync('python3',[new URL('./replay.py',import.meta.url).pathname],{encoding:'utf8',maxBuffer:8*1024*1024});
assert.equal(extraction.status,0,extraction.stderr);
const x=JSON.parse(extraction.stdout);
const names=dir=>fs.readdirSync(dir,{recursive:true,withFileTypes:true}).filter(e=>e.isFile()).map(e=>path.relative(dir,path.join(e.parentPath??e.path,e.name)));
const initialFiles=new Set(names(x.source));
const originals=new Map(names(x.originals).map(p=>[p,fs.readFileSync(path.join(x.originals,p),'utf8')]));
const read=p=>Object.hasOwn(x.changed,p)?x.changed[p]:fs.existsSync(path.join(x.source,p))?fs.readFileSync(path.join(x.source,p),'utf8'):null;
const pkg=JSON.parse(read('package.json'));
const inputs={initialFiles,originals,read,packages:new Map([['.',pkg]]),packageBytes:new Map([['.',read('package.json')]]),npmConfigs:new Map([['.',read('.npmrc')]])};
const make=()=>createPreservationNudge({directory:'/replay',inputs,initial:x.initial,save(){},active:()=>true,remainingMs:()=>1016882});
const event=x.events[91], snapshot={snapshotSha256:event.after,diff:x.diff};
const n=make(), text=n.after(event,snapshot,x.events.slice(0,92));
assert.ok(text,JSON.stringify(n.state));n.attached(event.callID,text);
const zero=make();assert.equal(zero.after(x.events[92],snapshot,x.events),null);
const rows=mochaReport(event.output.split('> mocha --opts mocha.opts --grep css-scoping-class\n')[1]);
assert.equal(rows.length,4);assert.equal(rows.filter(c=>c.suite==='runtime').length,3);assert.equal(rows.filter(c=>c.suite==='ssr').length,1);
console.log(JSON.stringify({replay:'passed',event:91,beforeSnapshotEdits:105,observedPasses:4,zeroTestControl:zero.state.reason,delivery:'offline attachment simulation only; historical author did not receive this advisory',state:n.state,provenance:x.provenance},null,2));
