// Run once after the authorized corrected preflight; commit manifest before dispatch.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {manifest} from '../native-task-integrated/run.mjs';import {reviewContext} from '../../lib/native-review-context.mjs';
const root=path.resolve('local/ledger-review-diagnostic'),dev='development/ledger-review-diagnostic',get=p=>JSON.parse(fs.readFileSync(p)),hash=b=>createHash('sha256').update(b).digest('hex');
const f=get(root+'/prepared-corrected.json'),p=get(dev+'/provenance.json'),preflight=get(dev+'/preflight.json');assert.equal(preflight.passed,true);assert.equal(preflight.scriptedSessions,1);assert.equal(preflight.scriptedRequests,3);
f.preflightPassed=true;f.taskSha256=p.taskSha256;f.expectedCandidates=Object.fromEntries(p.assignments.map(a=>[a.arm,a]));
for(const a of f.attempts){assert.deepEqual(manifest(a.source),f.inputManifests[a.task+'-'+a.arm]);const s=reviewContext({cwd:a.source,base:f.expectedCandidates[a.arm].base,taskFile:a.source+'/TASK.md',permissionRules:[{permission:'read',pattern:'*',action:'allow'}]});assert.equal(s.status,'captured');assert.equal(hash(fs.readFileSync(root+'/'+a.arm+'.patch')),f.expectedCandidates[a.arm].patchSha256);f.expectedCandidates[a.arm].workingSnapshotSha256=s.snapshotSha256;assert.equal(s.taskSha256,p.taskSha256);}
assert.deepEqual(manifest(f.template),f.runtimeManifests[f.template]);
const files=[...fs.readdirSync(dev).filter(n=>!['manifest.json','REPORT.md','result.json'].includes(n)).map(n=>dev+'/'+n),'development/native-task-ab/run-comparison.mjs','development/native-task-ab/provider-recording.mjs','development/native-task-abc/native-run.mjs','development/native-task-integrated/container-session.mjs','development/native-task-integrated/container-relay.mjs','development/native-task-utility/container/stop-workload.mjs','development/polybench-pilot/capture.mjs','development/native-output-retention/output-files.mjs','development/native-task-ab/extract-candidate.py','lib/native-review-context.mjs','lib/native-template.mjs','profiles/native/review.md','profiles/native/core.md','agents/core-reviewer.md',f.toolchain+'/package/bin/opencode'];
for(const file of files)f.files[path.resolve(file)]=hash(fs.readFileSync(file));
for(const name of ['attempt.json','outcome.json','scheduling-paused.json']){const file=root+'/preflight/'+name;f.files[file]=hash(fs.readFileSync(file));}
fs.mkdirSync(root+'/batch',{mode:0o700});fs.writeFileSync(root+'/batch/freeze.json',JSON.stringify(f,null,2)+'\n',{flag:'wx',mode:0o600});
fs.writeFileSync(dev+'/manifest.json',JSON.stringify({stage:'frozen-before-real-requests',freezeSha256:hash(fs.readFileSync(root+'/batch/freeze.json')),runtimeSha:f.runtimeSha,model:f.model,reasoning:f.variant,budgetSeconds:600,opencode:'1.18.26',image:f.image,resources:{cpus:2,memoryMb:3072,workMemoryMb:1536,pids:512,network:'none',user:'node'},taskSha256:f.taskSha256,assignments:p.assignments.map(a=>({...a,status:'not_started'})),bundleSha256:hash(JSON.stringify(f.runtimeManifests[f.template])),preflightSha256:hash(fs.readFileSync(dev+'/preflight.json')),files:Object.fromEntries(Object.entries(f.files).map(([p,h])=>[path.relative(process.cwd(),p),h])),decision:'Both reviewers finish; at least one concrete confirmed AR0 contract defect; no confirmed false mandatory control finding. Otherwise mixed, negative or unproven as in PLAN.',realProviderRequestsBeforeFreeze:0},null,2)+'\n',{flag:'wx'});
console.log('Frozen; local commit required before real dispatch.');
