// One neutral scripted native session, using the identical review command adapter.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {execFileSync,spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';
import {manifest} from '../native-task-integrated/run.mjs';import {run} from './run.mjs';
const root=path.resolve('local/ledger-review-diagnostic/preflight-corrected'),get=p=>JSON.parse(fs.readFileSync(p)),hash=b=>createHash('sha256').update(b).digest('hex');fs.mkdirSync(root,{mode:0o700});
const source=root+'/input';fs.mkdirSync(source);const git=(...args)=>execFileSync('git',args,{cwd:source});
fs.writeFileSync(source+'/index.cjs','exports.double = value => value * 2;\n');git('init','-q');git('add','.');git('-c','user.name=Fixture','-c','user.email=fixture@localhost','commit','-qm','Baseline');git('reflog','expire','--expire=all','--all');
fs.writeFileSync(source+'/index.cjs','exports.double = value => value * 3;\n');fs.writeFileSync(source+'/added.txt','NEUTRAL_UNTRACKED_SENTINEL\n');fs.appendFileSync(source+'/.git/info/exclude','\n/TASK.md\n');
const task='Review the change to double(value): multiply all numeric inputs by three, retaining the public function name. NEUTRAL_ORIGINAL_TASK_SENTINEL';fs.writeFileSync(source+'/TASK.md',task);
const f=get('local/ledger-review-diagnostic/prepared-corrected.json');Object.assign(f,{experimentKind:'ledger-review-diagnostic-preflight',preflightPassed:true,attempts:[{slot:1,task:'neutral-review',arm:'candidate-A',project:'local/neutral-review',source}],inputManifests:{'neutral-review-candidate-A':manifest(source)}});fs.writeFileSync(root+'/freeze.json',JSON.stringify(f,null,2));
let seq=0,work=0;const sent=[],errors=[];const started=Date.now();
try{
 const outcome=await run(root,{readAuth:()=>({access:'scripted-not-a-credential',accountId:'local'}),fetchImpl:async(url,options)=>{
  assert.equal(url,'https://chatgpt.com/backend-api/codex/responses');const body=JSON.parse(options.body),all=JSON.stringify(body),names=(body.tools??[]).map(t=>t.name);const main=names.length>0;let call;
  if(main){for(const n of ['read','glob','grep'])assert.ok(names.includes(n));for(const n of ['bash','edit','write','apply_patch','task','todowrite','harness_task'])assert.ok(!names.includes(n));assert.ok(all.includes(task));assert.ok(all.includes('NEUTRAL_UNTRACKED_SENTINEL'));assert.ok(all.includes('snapshotSha256'));assert.ok(all.includes('value * 3'));assert.ok(!all.includes('Implement the complete original task'));
   if(work++===0)call={name:'read',args:{filePath:'index.cjs'}};else assert.ok(all.includes('exports.double = value =&gt; value * 3;')||all.includes('exports.double = value => value * 3;'));
  }
  const id='resp_review_fixture_'+(++seq),item=call?{id:'fc_'+seq,type:'function_call',call_id:'call_'+seq,name:call.name,arguments:JSON.stringify(call.args),status:'completed'}:{id:'msg_'+seq,type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:'Neutral transport fixture. Checks NOT RUN. files_changed: []. Diagnostic-only termination.',annotations:[]}]};
  const base={id,object:'response',created_at:1,model:body.model,status:'in_progress',output:[]};const events=[{type:'response.created',response:base},{type:'response.output_item.added',output_index:0,item:call?{...item,arguments:'',status:'in_progress'}:{...item,status:'in_progress',content:[]}}];
  if(call)events.push({type:'response.function_call_arguments.delta',item_id:item.id,output_index:0,delta:item.arguments});else events.push({type:'response.content_part.added',item_id:item.id,output_index:0,content_index:0,part:{type:'output_text',text:'',annotations:[]}},{type:'response.output_text.delta',item_id:item.id,output_index:0,content_index:0,delta:item.content[0].text});
  events.push({type:'response.output_item.done',output_index:0,item},{type:'response.completed',response:{...base,status:'completed',output:[item],usage:{input_tokens:1,output_tokens:1,total_tokens:2}}});const bytes=Buffer.from(events.map(e=>'data: '+JSON.stringify(e)+'\n\n').join(''));sent.push(bytes);return new Response(bytes,{status:200,headers:{'content-type':'text/event-stream','x-request-id':id}});
 }});
 assert.equal(outcome.status,'finished',JSON.stringify(outcome));const out=root+'/runs/neutral-review-candidate-A',result=get(out+'/result.json'),snapshot=get(out+'/snapshot-before.json'),records=get(out+'/provider-metadata.json'),integrity=get(out+'/review-integrity.json'),stop=get(out+'/stop-verification.json');
 assert.equal(result.nativeCompleted,true);assert.equal(work,2);assert.equal(snapshot.task,task);assert.equal(snapshot.base,execFileSync('git',['rev-parse','HEAD'],{cwd:source,encoding:'utf8'}).trim());assert.deepEqual(snapshot.untracked,['added.txt']);assert.ok(integrity.nativeReads===1);assert.ok(stop.captureSaved&&stop.relayRemoved&&stop.terminationVerified);
 for(const [i,r]of records.entries()){assert.equal(r.recording.evidenceComplete,true);assert.ok(fs.readFileSync(out+'/response-'+r.requestIndex+'.sse').equals(sent[i]));assert.ok(fs.existsSync(out+'/upstream-request-'+r.requestIndex+'.json'));}
 const name=get(out+'/session/container.json').name,inspect=spawnSync('docker',['inspect',name],{encoding:'utf8'});assert.notEqual(inspect.status,0);assert.match(inspect.stderr,/no such object/i);
 fs.writeFileSync('development/ledger-review-diagnostic/preflight.json',JSON.stringify({passed:true,scriptedSessions:1,scriptedRequests:seq,realProviderRequests:0,elapsedMs:Date.now()-started,fullTask:true,explicitBase:true,trackedAndUntrackedSnapshot:true,nativeRead:true,forbiddenToolsAbsent:true,implementationStages:0,recording:'research-full-v1',rawStreamsVerified:true,integrity,stop,resultSha256:hash(fs.readFileSync(out+'/result.json'))},null,2)+'\n');
 console.log(JSON.stringify({passed:true,scriptedRequests:seq,realProviderRequests:0}));
}catch(e){errors.push(e.message);throw e;}finally{fs.writeFileSync(root+'/attempt.json',JSON.stringify({scriptedRequests:seq,errors,realProviderRequests:0,elapsedMs:Date.now()-started},null,2));}
