// Thin command adapter; the existing scheduler, transport and collector own lifecycle.
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';import {spawn,execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';
import {runComparison} from '../native-task-ab/run-comparison.mjs';import {startContainer} from '../native-task-integrated/container-session.mjs';import {runNativePhase} from '../native-task-abc/native-run.mjs';import {stopWorkload} from '../native-task-utility/container/stop-workload.mjs';import {captureCandidate} from '../polybench-pilot/capture.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');const get=p=>JSON.parse(fs.readFileSync(p));const save=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n',{flag:'wx',mode:0o600});
export async function run(root,extra={}){
 const f=get(root+'/freeze.json');
 if(!extra.fetchImpl){assert.equal(f.experimentKind,'ledger-review-diagnostic');assert.equal(f.preflightPassed,true);const commit=get(root+'/freeze-commit.json').commit;const b=execFileSync('git',['show',commit+':development/ledger-review-diagnostic/manifest.json']);assert.ok(b.equals(fs.readFileSync('development/ledger-review-diagnostic/manifest.json')));assert.equal(JSON.parse(b).freezeSha256,hash(fs.readFileSync(root+'/freeze.json')));}
 const env=s=>['OPENCODE_CONFIG_DIR=/template','OPENCODE_BIN=/opt/opencode','OPENCODE_CONFIG_CONTENT='+JSON.stringify(f.config),'HARNESS_REVIEW_BASE='+s.baseline,'HARNESS_REVIEW_TASK_FILE=/work/repo/TASK.md','PATH=/work/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'];
 const snapshot=s=>{const r=s.exec(['env',...env(s),'node','/template/review-context.mjs']);assert.equal(r.status,0,r.stderr);const v=JSON.parse(r.stdout);assert.equal(v.status,'captured',JSON.stringify(v));return v;};
 return runComparison({root,startContainer:async o=>{
  const s=await startContainer({...o,workMemoryMb:1536,memoryMb:3072});try{const r=s.exec(['git','rev-parse','HEAD^']);assert.equal(r.status,0,r.stderr);s.baseline=r.stdout.trim();if(f.experimentKind==='ledger-review-diagnostic-preflight')assert.equal(s.exec(['git','rm','--cached','added.txt']).status,0);assert.equal(s.exec(['git','rev-list','--all','--count']).stdout.trim(),'2');assert.equal(s.exec(['git','remote']).stdout.trim(),'');assert.equal(s.exec(['git','reflog','expire','--expire=all','--all']).status,0);return s;}catch(e){s.close();throw e;}
 },runTaskImplementation:async(s,o)=>{
  s.arm=o.arm;s.before=snapshot(s);assert.equal(s.before.task,o.task);if(f.experimentKind==='ledger-review-diagnostic'){const expected=f.expectedCandidates[o.arm];assert.equal(s.before.base,expected.base);assert.equal(hash(s.before.diff),expected.patchSha256);assert.equal(s.before.taskSha256,f.taskSha256);}save(path.dirname(s.output)+'/snapshot-before.json',s.before);
  const r=await runNativePhase(s,o,{spawnProcess:(cmd,args,settings)=>{const at=args.indexOf(s.name);assert.ok(at>0);const after=args.slice(at);const command=after.indexOf('harness-task');assert.ok(command>0);after[command]='harness-review';after[after.indexOf('--agent')+1]='harness-reviewer';return spawn(cmd,['exec','--workdir','/work/repo',...env(s).flatMap(v=>['--env',v]),...after],settings);}});
  const {events,stderr,...result}=r;return {...result,phaseCount:1,implementationStages:0,continuationApplied:false,nativeCompleted:r.exitCode===0&&!r.timedOut&&!r.parseErrors&&!events.some(e=>e.type==='error')&&events.some(e=>e.type==='step_finish'&&e.part?.reason==='stop')};
 },captureCandidate:Object.assign((s,out)=>{const after=snapshot(s);save(out+'/snapshot-after.json',after);assert.deepEqual(after,s.before,'Review snapshot changed');const r=captureCandidate(s,out);if(r.status===0){const native=get(out+'/native-evidence.json');assert.ok(native.sessions.every(x=>!x.parent_id));assert.ok(native.tools.every(x=>['read','glob','grep'].includes(x.data.tool)));assert.ok(!native.messages.some(x=>['build','harness-author'].includes(x.data.agent)));save(out+'/review-integrity.json',{snapshotUnchanged:true,snapshotSha256:after.snapshotSha256,taskSha256:after.taskSha256,base:after.base,head:after.head,implementationStages:0,nativeReads:native.tools.length,tools:[...new Set(native.tools.map(x=>x.data.tool))],sessions:native.sessions.length});}return r;},{requiresOutputRetention:true}),stopWorkload,readAuth:()=>{const a=get(path.join(os.homedir(),'.local/share/opencode/auth.json')).openai;if(a?.type!=='oauth'||!a.access||!a.accountId||a.expires<=Date.now())throw Error('Existing authorization unavailable or expired');return {access:a.access,accountId:a.accountId};},...extra});
}
if(process.argv[1]===fileURLToPath(import.meta.url))await run(path.resolve(process.argv[2]??'local/ledger-review-diagnostic/batch'));
