// Safe final extraction after both scheduled slots have ended; never feeds reviewer context.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
const root=path.resolve('local/ledger-review-diagnostic/batch'),dev='development/ledger-review-diagnostic',get=p=>JSON.parse(fs.readFileSync(p)),hash=b=>createHash('sha256').update(b).digest('hex');
const outcome=get(root+'/outcome.json'),freeze=get(root+'/freeze.json'),rows=[];
for(const a of freeze.attempts){const d=root+'/runs/'+a.task+'-'+a.arm;if(!fs.existsSync(d)){rows.push({slot:a.slot,candidate:a.arm,status:'not_started',requests:0,usage:null});continue;}
 const r=fs.existsSync(d+'/result.json')?get(d+'/result.json'):null,records=get(d+'/provider-metadata.json'),stop=get(d+'/stop-verification.json'),integrity=fs.existsSync(d+'/review-integrity.json')?get(d+'/review-integrity.json'):null;
 const events=fs.existsSync(d+'/session/events.jsonl')?fs.readFileSync(d+'/session/events.jsonl','utf8').trim().split('\n').filter(Boolean).map(JSON.parse):[];
 const final=events.filter(x=>x.type==='step_finish'&&x.part.reason==='stop').at(-1),parts=events.filter(x=>x.type==='text'&&x.part.messageID===final?.part.messageID).map(x=>x.part.text);
 if(parts.length){fs.writeFileSync(dev+'/'+a.arm+'-response.json',JSON.stringify({parts},null,2)+'\n',{});fs.writeFileSync(dev+'/'+a.arm+'-response.md',parts.join('\n\n'),{});}
 const usage={},byRole={};for(const record of records.filter(r=>r.forwarded)){const role=record.requestKind;byRole[role]??={requests:0,unknownUsage:0,input_tokens:0,output_tokens:0,cached_tokens:0,reasoning_tokens:0};byRole[role].requests++;if(!record.usage){byRole[role].unknownUsage++;continue;}for(const k of ['input_tokens','output_tokens','cached_tokens','reasoning_tokens']){usage[k]=(usage[k]??0)+(record.usage[k]??0);byRole[role][k]+=record.usage[k]??0;}}
 const initial=get(d+'/snapshot-before.json');assert.equal(initial.taskSha256,freeze.taskSha256);assert.equal(hash(initial.diff),freeze.expectedCandidates[a.arm].patchSha256);
 const work=records.filter(x=>x.forwarded&&x.requestKind==='work');for(const record of work){const body=get(d+'/upstream-request-'+record.requestIndex+'.json'),names=body.tools.map(t=>t.name);assert.ok(['read','glob','grep'].every(n=>names.includes(n)));assert.ok(!names.some(n=>['bash','edit','write','apply_patch','task','todowrite','harness_task'].includes(n)));const texts=body.input.flatMap(x=>Array.isArray(x.content)?x.content.map(c=>c.text??''):[]);assert.ok(texts.some(text=>text.includes(JSON.stringify(initial.task))));assert.ok(texts.some(text=>text.includes(initial.snapshotSha256)));}
 const archives=[];for(const record of records.filter(r=>r.forwarded)){assert.equal(record.recording.evidenceComplete,true);for(const name of ['request-'+record.requestIndex+'.json','upstream-request-'+record.requestIndex+'.json','response-'+record.requestIndex+'.sse']){const b=fs.readFileSync(d+'/'+name);archives.push({name,bytes:b.length,sha256:hash(b)});}}
 const receipts=['result.json','stop-verification.json','provider-metadata.json','native-evidence.json','review-integrity.json','snapshot-before.json','snapshot-after.json','model.patch','native-output/manifest.json'].filter(n=>fs.existsSync(d+'/'+n)).map(name=>{const b=fs.readFileSync(d+'/'+name);return {name,bytes:b.length,sha256:hash(b)};});
 rows.push({slot:a.slot,candidate:a.arm,status:r?.nativeCompleted?'completed':'incomplete',normalCompletion:r?.nativeCompleted??false,elapsedMs:r?.executionElapsedMs??null,requests:records.filter(x=>x.forwarded).length,unknownUsageRequests:records.filter(x=>x.forwarded&&!x.usage).length,usage,byRole,nativeReads:integrity?.nativeReads??null,integrity,stop,recording:'research-full-v1',offeredTools:[...new Set(work.flatMap(record=>get(d+'/upstream-request-'+record.requestIndex+'.json').tools.map(t=>t.name)))],rawRecords:archives,receipts,finalResponseParts:parts.length,responseSha256:parts.length?hash(fs.readFileSync(dev+'/'+a.arm+'-response.md')):null});
}
fs.writeFileSync(dev+'/review-results.json',JSON.stringify({outcome,rows,usageConvention:'Provider input/output totals; cached and reasoning tokens are included subsets, not added again. No monetary estimate.',preparation:{originalPreflightRequests:0,correctedPreflightRequests:3,schedulerMockDispatches:13,realRequests:0},implementationRuns:0,repairs:0},null,2)+'\n',{});console.log(JSON.stringify(rows.map(({rawRecords,receipts,...r})=>r),null,2));
