// Final evidence verification only. Does not dispatch native or provider requests.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import {manifest} from '../native-task-integrated/run.mjs';
const dev='development/ledger-review-diagnostic',root=path.resolve('local/ledger-review-diagnostic'),get=p=>JSON.parse(fs.readFileSync(p)),hash=b=>createHash('sha256').update(b).digest('hex');const f=get(root+'/batch/freeze.json'),r=get(dev+'/review-results.json'),findings=get(dev+'/findings.json');assert.equal(r.outcome.status,'finished');assert.equal(r.rows.length,2);const totals={requests:0,nativeReads:0,elapsedMs:0,input_tokens:0,output_tokens:0,cached_tokens:0,reasoning_tokens:0};
const commit=get(root+'/batch/freeze-commit.json').commit;assert.equal(hash(execFileSync('git',['show',commit+':'+dev+'/manifest.json'])),hash(fs.readFileSync(dev+'/manifest.json')));assert.equal(get(dev+'/manifest.json').freezeSha256,hash(fs.readFileSync(root+'/batch/freeze.json')));
for(const a of f.attempts){assert.deepEqual(manifest(a.source),f.inputManifests[a.task+'-'+a.arm]);const actualValidation=manifest(root+'/validation/'+a.arm),expected={...f.inputManifests[a.task+'-'+a.arm]};delete expected['TASK.md'];assert.deepEqual(actualValidation,expected);const row=r.rows.find(x=>x.candidate===a.arm),d=root+'/batch/runs/'+a.task+'-'+a.arm;assert.equal(row.normalCompletion,true);assert.ok(row.elapsedMs<=600000);assert.equal(row.unknownUsageRequests,0);assert.ok(row.stop.terminationVerified&&row.stop.captureSaved&&row.stop.forwardingClosed&&row.stop.relayRemoved&&row.stop.activeProviderHandlers===0);assert.deepEqual(get(d+'/snapshot-before.json'),get(d+'/snapshot-after.json'));assert.equal(hash(fs.readFileSync(d+'/model.patch')),f.expectedCandidates[a.arm].patchSha256);
 for(const x of [...row.rawRecords,...row.receipts]){const b=fs.readFileSync(d+'/'+x.name);assert.equal(b.length,x.bytes);assert.equal(hash(b),x.sha256);}
 const meta=get(d+'/provider-metadata.json');assert.equal(meta.filter(x=>x.forwarded).length,row.requests);const first=meta.find(x=>x.requestKind==='work');const body=get(d+'/upstream-request-'+first.requestIndex+'.json'),snapshot=get(d+'/snapshot-before.json');assert.ok(body.input.flatMap(x=>x.content??[]).some(c=>c.text?.includes(JSON.stringify(snapshot))),'Exact full task/base/diff snapshot must reach first work request');
 const events=fs.readFileSync(d+'/session/events.jsonl','utf8').trim().split('\n').map(JSON.parse),stopEvent=events.filter(e=>e.type==='step_finish'&&e.part.reason==='stop').at(-1),texts=events.filter(e=>e.type==='text'&&e.part.messageID===stopEvent.part.messageID).map(e=>e.part.text);assert.deepEqual(get(dev+'/'+a.arm+'-response.json').parts,texts);assert.equal(texts.length,1);assert.equal(fs.readFileSync(dev+'/'+a.arm+'-response.md','utf8'),texts[0]);
 const native=get(d+'/native-evidence.json');assert.equal(native.sessions.length,1);assert.ok(native.tools.every(t=>['read','glob','grep'].includes(t.data.tool)));assert.ok(native.messages.every(m=>m.data.agent==='harness-reviewer'));assert.ok(native.messages.filter(m=>m.data.role==='assistant').every(m=>m.data.modelID==='gpt-5.6-luna'&&m.data.variant==='high'));
 for(const k of ['input_tokens','output_tokens','cached_tokens','reasoning_tokens']){const sum=meta.reduce((n,x)=>n+(x.usage?.[k]??0),0);assert.equal(sum,row.usage[k]);assert.equal(sum,Object.values(row.byRole).reduce((n,x)=>n+x[k],0));totals[k]+=sum;}for(const k of ['requests','nativeReads','elapsedMs'])totals[k]+=row[k];
}
assert.equal(totals.requests,27);assert.equal(totals.nativeReads,47);assert.equal(findings.findings.filter(x=>x.candidate==='candidate-A'&&x.classification==='confirmed').length,3);assert.equal(findings.findings.filter(x=>x.candidate==='candidate-B'&&x.classification==='confirmed').length,4);assert.equal(findings.knownAR0Misses.length,4);
for(const x of findings.receipts){const b=fs.readFileSync(dev+'/'+x.file);assert.equal(b.length,x.bytes);assert.equal(hash(b),x.sha256);}
for(const [file,digest] of Object.entries(f.files))assert.equal(hash(fs.readFileSync(file)),digest,'Frozen execution file changed: '+file);
fs.writeFileSync(dev+'/result.json',JSON.stringify({status:'two-reviews-completed',rows:r.rows.map(({rawRecords,receipts,...x})=>({...x,findings:findings.counts[x.candidate]})),totals,recording:'research-full-v1; all 27 provider records complete',unknownUsageRequests:0,implementationRuns:0,repairs:0,modelRetries:0,preparation:{installedAttempts:2,first:'failed before request',corrected:'passed',scriptedNativeSessions:1,scriptedRequests:3,schedulerMockDispatches:13},protocolDeviation:'Native skill tool was offered in both sessions and corrected preflight, but never called. Exact three-tool inventory not achieved; no forbidden write/Bash/delegation was called.',decision:findings.decision},null,2)+'\n');fs.writeFileSync(dev+'/verification.json',JSON.stringify({passed:true,exactFrozenCommit:commit,sourceAndValidationCopiesUnchanged:true,completeSnapshotsInFirstRequests:true,rawRecordingHashesVerified:true,originalResponsesUnchanged:true,usageArithmetic:true,allFrozenExecutionFilesUnchanged:true,totals,modelCallsByVerifier:0,scope:'Artifact/custody/accounting checks; not a second review or model-quality proof'},null,2)+'\n');console.log(JSON.stringify({passed:true,totals}));
