// Structural/custody and accounting checks only; no native execution or provider calls.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';
import {manifest} from '../native-task-integrated/run.mjs';import {reviewContext} from '../../lib/native-review-context.mjs';
const get=p=>JSON.parse(fs.readFileSync(p)),hash=b=>createHash('sha256').update(b).digest('hex');const root=path.resolve('local/ledger-review-diagnostic'),dev='development/ledger-review-diagnostic',f=get(root+'/prepared.json'),p=get(dev+'/provenance.json');const snapshots=[];
assert.equal(f.preflightPassed,false);assert.ok(!fs.existsSync(root+'/batch'));assert.equal(f.budgetMs,600000);assert.equal(f.strategy,'diagnostic-review');
for(const a of f.attempts){assert.deepEqual(manifest(a.source),f.inputManifests[a.task+'-'+a.arm]);const provenance=p.assignments.find(x=>x.arm===a.arm);const s=reviewContext({cwd:a.source,base:provenance.base,taskFile:a.source+'/TASK.md',permissionRules:[{permission:'read',pattern:'*',action:'allow'}]});assert.equal(s.status,'captured');assert.equal(s.taskSha256,p.taskSha256);const git=(...args)=>execFileSync('git',args,{cwd:a.source,encoding:'utf8'}).trim();assert.equal(git('rev-list','--all','--count'),'1');assert.equal(git('remote'),'');assert.equal(git('reflog','--all'),'');assert.equal(hash(fs.readFileSync(root+'/'+a.arm+'.patch')),provenance.patchSha256);snapshots.push({candidate:a.arm,base:s.base,head:s.head,snapshotSha256:s.snapshotSha256,diffBytes:Buffer.byteLength(s.diff),untracked:s.untracked,taskSha256:s.taskSha256,scope:'host structural read-rule fixture only; not installed reviewer proof'});}
assert.deepEqual(manifest(f.template),f.runtimeManifests[f.template]);const config=get(f.template+'/opencode.json');assert.deepEqual(Object.keys(config.command),['harness-review']);assert.equal(config.agent['harness-reviewer'].mode,'primary');assert.deepEqual(config.agent['harness-reviewer'].permission,{edit:'deny',bash:'deny',task:'deny',todowrite:'deny'});assert.ok(!fs.existsSync(f.template+'/.gitignore'));assert.ok(!fs.existsSync(f.template+'/native-task-plugin.mjs'));
for(const file of ['core.md','review-context.mjs'])assert.ok(fs.readFileSync(f.template+'/'+file).equals(fs.readFileSync(file==='core.md'?'profiles/native/core.md':'lib/native-review-context.mjs')));
const out=root+'/preflight/runs/neutral-review-candidate-A',attempt=get(root+'/preflight/attempt.json'),provider=get(out+'/provider-metadata.json'),recovery=get(out+'/recovery.json'),native=get(out+'/native-evidence.json');assert.equal(attempt.scriptedRequests,0);assert.equal(provider.length,0);assert.equal(native.sessions.length,0);assert.equal(native.messages.length,0);assert.equal(native.tools.length,0);assert.equal(recovery.newProviderRequests,0);assert.equal(recovery.result.status,0);
const receiptFiles=['attempt.json','outcome.json','scheduling-paused.json'].map(n=>root+'/preflight/'+n).concat(['provider-metadata.json','native-evidence.json','stop-verification.json','recovery.json','capture-error.json','session/retained-resource.json','evidence-capture.json','native-output/manifest.json'].map(n=>out+'/'+n));
const receipts=receiptFiles.map(file=>{const bytes=fs.readFileSync(file);return {file:path.relative(process.cwd(),file),bytes:bytes.length,sha256:hash(bytes)};});
const scheduler=get(dev+'/scheduler-checks.json');assert.equal(scheduler.passed,true);assert.equal(scheduler.scenarios,16);assert.equal(scheduler.mockProviderDispatches,13);assert.equal(scheduler.realProviderRequests,0);
const result={schedulerRegression:scheduler,preparationStructuralChecksPassed:true,installedPreflightPassed:false,scriptedPreflightAttempts:1,scriptedNativeSessions:0,scriptedRequests:0,realReviewerSessions:0,realProviderRequests:0,implementationRuns:0,reviewerUsage:{input:0,output:0,cachedSubset:0,reasoningSubset:0,unknownUsageRequests:0},preflightElapsedMs:attempt.elapsedMs,slots:f.attempts.map(a=>({slot:a.slot,candidate:a.arm,status:'not_started',normalCompletion:null,findings:null,misses:null,elapsedMs:0,requests:0,nativeReads:0})),snapshots,receipts,recovery:{copiedExistingDataOnly:recovery.copiedExistingDataOnly,newProviderRequests:0,evidenceComplete:true,containerRemoved:true},missingChecks:['Installed full task/base/diff delivery','Native read and actual provider tool inventory','Request/raw response recording in a reviewer session','Normal reviewer completion','Real reviewer utility and findings validation'],decision:'unproven: preparation blocker; no model observations'};
fs.writeFileSync(dev+'/result.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({structuralChecksPassed:true,preflightPassed:false,scriptedRequests:0,realRequests:0,realSlots:'not_started'}));
