import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
const local=path.resolve('local/preservation-nudge-revision-2-model-pair'),dev='development/preservation-nudge/revision-2/model-pair',get=p=>JSON.parse(fs.readFileSync(p)),hash=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex'),save=(p,x)=>fs.writeFileSync(p,JSON.stringify(x,null,2)+'\n');
assert.ok(!fs.existsSync(local+'/batch'));
const preflight=get(dev+'/preflight.json'),calibration=get('local/preservation-nudge-model-pair/calibration/summary.json');assert.equal(preflight.passed,true);assert.equal(calibration.calibration_passed,true);assert.deepEqual([...calibration.created_containers].sort(),[...calibration.removed_containers].sort());
const names=execFileSync('docker',['ps','--format','{{.Names}}'],{encoding:'utf8'}).trim().split('\n').filter(Boolean);assert.ok(!names.some(n=>/^(template-dev-|preservation-|polybench-)/.test(n)),'Prior live local execution');
const reuse=get(local+'/calibration-reuse.json');assert.equal(reuse.reused,true);for(const [key,file] of Object.entries({driver:'development/polybench-pilot/two-world-diagnostic/driver.py',adapter:'development/preservation-nudge/model-pair/evaluate.py',manifest:'development/polybench-pilot/two-world-diagnostic/sveltejs__svelte-1190.json'}))assert.equal(hash(file),calibration.identity[key]);
const f=get(local+'/prepared.json');f.experimentKind='preservation-pair';f.controlsPassed=true;f.authorIsolationPassed=true;
for(const file of ['development/preservation-nudge/model-pair/run.mjs','development/preservation-nudge/model-pair/evaluate.py',dev+'/prepare.mjs',dev+'/preflight.mjs',dev+'/advisory-preflight.mjs',dev+'/verify-preflight.mjs',dev+'/verify-schedule.mjs',dev+'/freeze.mjs',dev+'/PLAN.md',dev+'/TASK.md',dev+'/preflight.json','development/native-task-ab/run-comparison.mjs','development/native-task-abc/native-run.mjs','development/native-task-integrated/container-session.mjs','development/native-task-integrated/container-relay.mjs','development/native-task-utility/container/stop-workload.mjs','development/polybench-pilot/capture.mjs','development/polybench-pilot/dependencies.mjs','development/native-task-ab/extract-candidate.py','development/native-task-offline/build.json','development/polybench-pilot/two-world-diagnostic/driver.py','development/polybench-pilot/two-world-diagnostic/sveltejs__svelte-1190.json',f.toolchain+'/package/bin/opencode'])f.files[path.resolve(file)]=hash(file);
const preservationFiles=['freeze.json','freeze-commit.json','scheduling-paused.json','outcome.json'];for(const n of preservationFiles){const file=path.resolve('local/polybench-pilot/batch/'+n);f.files[file]=hash(file);}
for(const n of ['freeze.json','freeze-commit.json','outcome.json']){const file=path.resolve('local/preservation-nudge-model-pair/batch/'+n);f.files[file]=hash(file);}
const task=get(local+'/input-receipt.json').task;assert.equal(execFileSync('docker',['image','inspect',task.authorImage,'--format','{{.Id}}'],{encoding:'utf8'}).trim(),task.authorImage);
assert.equal(execFileSync('docker',['image','inspect',task.officialImage.digest,'--format','{{.Id}}'],{encoding:'utf8'}).trim(),task.officialImage.id);
fs.mkdirSync(local+'/batch',{mode:0o700});save(local+'/batch/freeze.json',f);
const safeCalibration=structuredClone(calibration);delete safeCalibration.created_containers;delete safeCalibration.removed_containers;save(dev+'/calibration.json',safeCalibration);
const published={version:1,preservationRevision:2,calibrationReuse:reuse,stage:'frozen_before_model_requests',runtimeSha:f.runtimeSha,freezeSha256:hash(local+'/batch/freeze.json'),task,model:f.model,opencode:'1.18.26',reasoning:f.variant,budgetSeconds:1800,flags:{STRATEGY:'direct',CONTEXT:0,CHECKS:0,TYPE_COMPAT:0,SENSITIVITY:0,INVESTIGATION:0,COMMAND_HINTS:0,EXTRA_ATTENTION:0,PRESERVATION_NUDGE:{OFF:0,ON:1}},slots:f.attempts.map(({source,...a})=>({...a,status:'not_started',A:null,Q_pair:null,T:null,D_pair:null})),inputReceipt:get(local+'/input-receipt.json'),config:f.config,offlineConfig:get('development/native-task-offline/build.json'),files:Object.fromEntries(Object.entries(f.files).map(([p,h])=>[p.startsWith(process.cwd()+'/')?p.slice(process.cwd().length+1):path.basename(p),h])),calibrationSha256:hash(dev+'/calibration.json'),preflightSha256:hash(dev+'/preflight.json'),priorLiveExecutionAbsent:true,priorPauseFilesPreserved:true,realProviderRequestsBeforeFreeze:0};
save(dev+'/manifest.json',published);console.log('Prepared local freeze; commit before real dispatch');
