import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import {manifest} from '../native-task-integrated/run.mjs';
const root=path.resolve('local/native-command-hints-comparison/batch'),dev=path.resolve('development/native-command-hints-comparison'),read=p=>JSON.parse(fs.readFileSync(p)),hash=b=>createHash('sha256').update(b).digest('hex');
assert.ok(!fs.existsSync(root+'/freeze.json'),'Never overwrite a freeze');assert.ok(!fs.existsSync(root+'/runs'));
const preflight=read(root+'/preflight.json'),audit=read(root+'/preflight-audit.json'),calibration=read(root+'/calibration.json');
assert.ok(preflight.passed&&preflight.realProviderRequests===0&&preflight.results.length===4&&preflight.results.every(r=>r.nativeCompleted&&r.termination.terminationVerified));assert.ok(audit.passed&&audit.results.length===4);
assert.equal(calibration.results.length,6);for(const r of calibration.results){assert.equal(r.accepted,r.label==='reference');if(r.label==='baseline')assert.ok(r.commands.filter(c=>c.name.startsWith('project-')).every(c=>c.status===0));else if(r.label==='incomplete')assert.notEqual(r.commands.find(c=>c.name==='independent-behavior').status,0);}
const runtimeSha='c90fc7c78bcdd4d8288550b887f52990bafb11a6',template=root+'/bundle';
for(const n of fs.readdirSync(template).filter(n=>n.endsWith('.mjs')))assert.ok(execFileSync('git',['show',runtimeSha+':lib/'+n]).equals(fs.readFileSync(template+'/'+n)),n);
assert.ok(execFileSync('git',['show',runtimeSha+':profiles/native/core.md']).equals(fs.readFileSync(template+'/core.md')));
const attempts=[['A','OFF'],['A','ON'],['B','ON'],['B','OFF']].map(([task,arm],i)=>({slot:i+1,task,arm,project:task==='A'?'unjs/ufo':'primus/eventemitter3',source:root+'/inputs/'+task}));
const runtimeManifests={},inputManifests={};for(const d of [template,...new Set(attempts.map(a=>a.source))])runtimeManifests[d]=manifest(d);for(const a of attempts)inputManifests[a.task+'-'+a.arm]=runtimeManifests[a.source];
const files={};const add=f=>files[path.resolve(f)]=hash(fs.readFileSync(f));
for(const n of fs.readdirSync(dev).filter(n=>n.endsWith('.mjs')||n==='PLAN.md'))add(dev+'/'+n);
for(const sub of ['tasks','evaluation'])for(const n of fs.readdirSync(dev+'/'+sub))add(dev+'/'+sub+'/'+n);
for(const n of ['development/native-task-ab/run-comparison.mjs','development/native-task-abc/native-run.mjs','development/native-task-integrated/native-run.mjs','development/native-task-integrated/container-session.mjs','development/native-task-integrated/container-relay.mjs','development/native-task-ab/capture-candidate.mjs','development/native-task-ab/extract-candidate.py','development/native-task-utility/container/stop-workload.mjs'])add(n);
for(const n of ['experiment-config.json','sources.json','calibration.json','preflight.json','preflight-audit.json'])add(root+'/'+n);
// Bind actual calibrated source/tests/docs, excluding duplicate dependency trees.
for(const task of ['A','B'])for(const label of ['reference','incomplete']){const base=root+'/calibration/'+task+'/'+label;function visit(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){if(e.name==='node_modules'||e.name==='.git')continue;const p=path.join(d,e.name);if(e.isDirectory())visit(p);else add(p);}}visit(base);}
const toolchain=path.resolve('../verified-change-harness/local/template-toolchain-20260908');add(toolchain+'/package/bin/opencode');
const containers=execFileSync('docker',['ps','-a','--format','{{.Names}}'],{encoding:'utf8'}).trim().split('\n').filter(n=>/^(template-dev-|command-hints-)/.test(n));assert.deepEqual(containers,[],'Prior native task/fixture container must be absent before new batch');
const f={version:1,experimentKind:'command-hints',createdAt:new Date().toISOString(),runtimeSha,model:'openai/gpt-5.6-luna',variant:'high',budgetMs:1800000,strategy:'direct',preflightPassed:true,streamLimit:'remaining-task-budget',connectionTimeoutMs:30000,toolchain,template,dependencies:template,config:read(root+'/experiment-config.json'),attempts,inputManifests,runtimeManifests,files};
fs.writeFileSync(root+'/freeze.json',JSON.stringify(f),{flag:'wx'});
const sources=read(root+'/sources.json');const publicFreeze={createdAt:f.createdAt,runtimeSha,freezeSha256:hash(fs.readFileSync(root+'/freeze.json')),model:f.model,effort:f.variant,taskDeadlineMs:f.budgetMs,permission:f.config.permission,authorization:'User explicitly approved identical external_directory allow in isolated OFF/ON containers after the deny eligibility report',order:attempts.map(({source,...a})=>a),inputs:['A','B'].map(task=>({task,project:sources[task].project,commit:sources[task].ref,inputManifestSha256:hash(JSON.stringify(runtimeManifests[root+'/inputs/'+task])),promptSha256:hash(fs.readFileSync(root+'/inputs/'+task+'/TASK.md'))})),preflight:{sessions:4,localRequests:preflight.results.reduce((s,r)=>s+r.requests.length,0),passed:true,realProviderRequests:0},calibration:calibration.results.map(({output,...r})=>r),files:Object.fromEntries(Object.entries(files).filter(([n])=>n.startsWith(path.resolve('development')+'/')).map(([n,h])=>[path.relative(process.cwd(),n),h])),priorContainers:[],realProviderRequestsBeforeFreeze:0};
fs.writeFileSync(dev+'/frozen-inputs.json',JSON.stringify(publicFreeze,null,2)+'\n',{flag:'wx'});fs.writeFileSync(dev+'/assigned.json',JSON.stringify(attempts.map(({source,...a})=>({...a,status:'not_started',Q:null,T:null,D:null})),null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({frozen:true,slots:4,hash:publicFreeze.freezeSha256,realProviderRequests:0}));
