// One local scripted preflight on actual inputs. Never reads provider credentials.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {startContainer} from '../native-task-integrated/container-session.mjs';import {runTask} from '../native-task-integrated/native-run.mjs';import {stopWorkload} from '../native-task-utility/container/stop-workload.mjs';
const root=path.resolve(process.argv[2]),toolchain=path.resolve('../verified-change-harness/local/template-toolchain-20260908');const config=JSON.parse(fs.readFileSync(root+'/experiment-config.json'));const results=[];
for(const [task,arm] of [['A','OFF'],['A','ON'],['B','ON'],['B','OFF']]){
 const source=root+'/inputs/'+task,text=fs.readFileSync(source+'/TASK.md','utf8'),requests=[],failures=[],counts=new Map();let seq=0,session;
 try{session=await startContainer({source,toolchain,template:root+(arm==='P'?'/plain-dependencies':'/bundle'),output:root+'/preflight-'+task+'-'+arm,workMemoryMb:1536,memoryMb:3072,onRequest:async(frame,send)=>{
  try{fs.writeFileSync(root+'/preflight-'+task+'-'+arm+'/request-'+(seq+1)+'.json',JSON.stringify(frame.body));const body=frame.body,all=JSON.stringify(body),inputs=body.input??[];const stage=!body.tools?.length?'title':all.includes('Implement the complete original task')?'author':arm==='P'?'author':'bootstrap';const n=counts.get(stage)??0;counts.set(stage,n+1);assert.equal(body.model,'gpt-5.6-luna');assert.equal(body.reasoning?.effort,'high');let call=null;
   if(stage==='bootstrap'&&n===0)call={name:'harness_task',args:{}};
   if(stage==='author'){
    assert.ok(all.includes(JSON.stringify(text.trim()).slice(1,-1)),'complete original task received');
    const names=body.tools.map(t=>t.name);assert.equal(config.permission.external_directory,'allow');assert.equal(names.includes('harness_sense'),arm==='Htools');assert.equal(names.includes('harness_investigate'),arm==='Htools');for(const tool of ['read','bash','apply_patch'])assert.ok(names.includes(tool));
    const outputs=inputs.filter(x=>x.type==='function_call_output').map(x=>typeof x.output==='string'?x.output:JSON.stringify(x.output));
    const last=outputs.at(-1)??'';
    const bash=command=>({name:'bash',args:{command,description:'Offline preparation check',workdir:'.',timeout:120000}});
    let route=null;
    if(n===2){assert.match(last,/worktree/);assert.ok(last.includes('HARNESS_TASK_COMMAND_HINTS'));assert.ok(last.includes(arm==='ON'?'COMMAND_HINTS=1':'COMMAND_HINTS=0'));for(const flag of ['CONTEXT','CHECKS','SENSITIVITY','INVESTIGATION','EXTRA_ATTENTION'])assert.ok(last.includes('HARNESS_TASK_'+flag+'=0'));}
    if(task==='A'&&n===3){assert.match(last,/pnpm: command not found/);const marker='Host-derived project command context:\n',at=last.indexOf(marker);if(arm==='ON'){assert.ok(at>=0,last);const hint=JSON.parse(last.slice(at+marker.length).trim());assert.equal(hint.status,'path-found');assert.equal(hint.scope,'partial-lint');route=hint.routes[0];}else assert.equal(at,-1);}
    const calls=[{name:'read',args:{filePath:'TASK.md'}},bash('pwd && env | sort | grep "^HARNESS_TASK_"'),bash(task==='A'?'pnpm test':'npm test'),bash(task==='A'?(route??'npm test'):'npm run test-esm'),bash(task==='A'?'npm test && npm run build':'npm run rollup'),{name:'apply_patch',args:{patchText:'*** Begin Patch\n*** Add File: PREFLIGHT.md\n+Local scripted preparation check.\n*** End Patch'}},bash('git diff --check')];
    call=calls[n]??null;

   }
   requests.push({stage,model:body.model,effort:body.reasoning?.effort,tools:body.tools?.map(t=>t.name)});
   const id='resp_scripted_'+(++seq),item=call?{id:'fc_'+seq,type:'function_call',call_id:'call_'+seq,name:call.name,arguments:JSON.stringify(call.args),status:'completed'}:{id:'msg_'+seq,type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:'Local scripted check ended. No quality claim.',annotations:[]}]};const base={id,object:'response',created_at:1,model:body.model,status:'in_progress',output:[]};const events=[{type:'response.created',response:base},{type:'response.output_item.added',output_index:0,item:call?{...item,arguments:'',status:'in_progress'}:{...item,status:'in_progress',content:[]}}];
   if(call)events.push({type:'response.function_call_arguments.delta',item_id:item.id,output_index:0,delta:item.arguments});else events.push({type:'response.content_part.added',item_id:item.id,output_index:0,content_index:0,part:{type:'output_text',text:'',annotations:[]}},{type:'response.output_text.delta',item_id:item.id,output_index:0,content_index:0,delta:item.content[0].text});events.push({type:'response.output_item.done',output_index:0,item},{type:'response.completed',response:{...base,status:'completed',output:[item],usage:{input_tokens:1,output_tokens:1,total_tokens:2}}});send({type:'headers',status:200,contentType:'text/event-stream'});send({type:'chunk',data:Buffer.from(events.map(e=>'data: '+JSON.stringify(e)+'\n\n').join('')).toString('base64')});send({type:'end'});
  }catch(e){failures.push(e.message);send({type:'headers',status:403,contentType:'text/plain'});send({type:'end'});}
 }});
 const setup=session.exec(['node','-e',"const fs=require('fs');fs.mkdirSync('/work/bin');fs.copyFileSync('/template/rg','/work/bin/rg');fs.chmodSync('/work/bin/rg',0o755);fs.mkdirSync('/work/config/opencode',{recursive:true});for(const n of ['node_modules','package.json','package-lock.json'])fs.cpSync('/template/'+n,'/work/config/opencode/'+n,{recursive:true,verbatimSymlinks:true});"]);assert.equal(setup.status,0,setup.stderr);assert.equal(session.exec(['/opt/opencode','--version']).stdout.trim(),'1.18.26');session.setTaskBudget(1800000);
 const result=await runTask(session,{config,task:text,enabled:arm!=='P',arm,model:'openai/gpt-5.6-luna',variant:'high',limitMs:1800000,stopWorkload});assert.deepEqual(failures,[]);assert.equal(result.nativeCompleted,true,JSON.stringify(result));assert.equal(result.termination.terminationVerified,true);
 const verify=session.exec(['node','-e',`const fs=require('fs'),{spawnSync}=require('child_process'),assert=require('assert/strict');let patch;if(${arm!=='P'}){const a='/work/repo/.git/harness-task/'+fs.readdirSync('/work/repo/.git/harness-task')[0];patch=fs.readFileSync(a+'/terminal.patch','utf8');assert.equal(fs.existsSync('/work/repo/PREFLIGHT.md'),false);for(const n of ['component-context.json','component-checks.json'])assert.equal(fs.existsSync(a+'/'+n),false);}else{spawnSync('git',['add','PREFLIGHT.md']);patch=spawnSync('git',['diff','--binary','HEAD'],{encoding:'utf8'}).stdout;}fs.cpSync('/input','/work/applied',{recursive:true,verbatimSymlinks:true});const r=spawnSync('git',['apply','--binary','-'],{cwd:'/work/applied',input:patch,encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.ok(fs.existsSync('/work/applied/PREFLIGHT.md'));console.log(JSON.stringify({portablePatch:true,originalPreserved:true}));`]);assert.equal(verify.status,0,verify.stderr);
 results.push({arm,task,...result,requests,patch:JSON.parse(verify.stdout),realProviderRequests:0});console.log(JSON.stringify({arm,passed:true,requests:requests.length}));
 }finally{if(session)assert.equal(session.close(),0);}
}
assert.deepEqual(results.map(r=>r.requests.find(q=>q.stage==='author').tools.slice().sort()),Array(4).fill(results[0].requests.find(q=>q.stage==='author').tools.slice().sort()));
fs.writeFileSync(root+'/preflight.json',JSON.stringify({passed:true,results,realProviderRequests:0},null,2),{flag:'wx'});
