// Existing installed native path and collector, with a loopback scripted provider.
import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';
import {runComparison} from '../native-task-ab/run-comparison.mjs';import {startContainer} from '../native-task-integrated/container-session.mjs';import {stopWorkload} from '../native-task-utility/container/stop-workload.mjs';import {captureCandidate} from '../polybench-pilot/capture.mjs';import {materializeNativeTemplate} from '../../lib/native-template.mjs';import {digest} from './fixture.mjs';import {runTask as installedTask} from '../direct-assertion-review/model-pair/run.mjs';
const repo=process.cwd(),root=path.resolve(process.argv[2]);fs.mkdirSync(root,{mode:0o700});
const dependencies=repo+'/local/native-task-integrated/plain-dependencies',bundle=root+'/bundle';materializeNativeTemplate({repositoryRoot:repo,outputDirectory:bundle,task:true});
for(const n of ['node_modules','package-lock.json','rg'])fs.cpSync(dependencies+'/'+n,bundle+'/'+n,{recursive:true,verbatimSymlinks:true});
const installedConfig=JSON.parse(fs.readFileSync(bundle+'/opencode.json'));installedConfig.instructions=['/template/core.md'];installedConfig.plugin=['file:///template/native-task-plugin.mjs'];fs.writeFileSync(bundle+'/opencode.json',JSON.stringify(installedConfig));
const templatePackage=JSON.parse(fs.readFileSync(bundle+'/package.json'));assert.ok(templatePackage);
const task='Change double(value) to triple(value). Preserve the exported function name double and reject non-number inputs with TypeError. Update the existing numeric expectation and retain rejection coverage. Run node --test.';
const attempts=[1,2].map(slot=>({slot,task:'triple-'+slot,arm:'H1',source:root+'/input-'+slot}));const manifests={};
for(const a of attempts){fs.mkdirSync(a.source);fs.writeFileSync(a.source+'/TASK.md',task);fs.writeFileSync(a.source+'/index.cjs',"exports.double = value => { if (typeof value !== 'number') throw new TypeError('number required'); return value * 2; };\n");fs.writeFileSync(a.source+'/index.test.cjs',"const test=require('node:test'),assert=require('node:assert/strict'),{double}=require('./index.cjs');\ntest('numeric and rejection',()=>{assert.equal(double(4),8);assert.throws(()=>double('4'),TypeError);});\n");manifests[a.task+'-'+a.arm]=Object.fromEntries(fs.readdirSync(a.source).map(n=>[n,{sha256:digest(fs.readFileSync(a.source+'/'+n)),executable:false}]));}
const old=JSON.parse(fs.readFileSync(repo+'/local/native-sensitivity/usage-20260914/freeze.json'));
const config=structuredClone(old.config);config.permission.webfetch='deny';config.agent={build:{permission:{webfetch:'deny'}}};
const freeze={experimentKind:'sensitivity-usage',model:old.model,variant:old.variant,strategy:'direct',budgetMs:900000,streamLimit:'remaining-task-budget',connectionTimeoutMs:30000,preflightPassed:true,files:{},attempts,inputManifests:manifests,toolchain:old.toolchain,template:bundle,config};fs.writeFileSync(root+'/freeze.json',JSON.stringify(freeze));
let seq=0,active,state;const responses=[],authorPrompts=[],errors=[],summaries=[];const started=Date.now();
const provider=http.createServer(async(req,res)=>{try{
 const chunks=[];for await(const c of req)chunks.push(c);const body=JSON.parse(Buffer.concat(chunks)),all=JSON.stringify(body);const names=(body.tools??[]).map(t=>t.name),title=!names.length,author=all.includes('Implement the complete original task');let call;if(!title&&!author)assert.ok(names.includes('harness_task'),'Missing installed harness tool');
 if(!title&&!author&&state.parent++===0)call={name:'harness_task',args:{}};
 if(!title&&author){assert.ok(!all.includes('During self-review,'));assert.ok(all.includes(task));authorPrompts.push(digest(Buffer.concat(chunks)));
 const sequence=[{name:'read',args:{filePath:'index.cjs'}},{name:'apply_patch',args:{patchText:"*** Begin Patch\n*** Update File: index.cjs\n@@\n-exports.double = value => { if (typeof value !== 'number') throw new TypeError('number required'); return value * 2; };\n+exports.double = value => { if (typeof value !== 'number') throw new TypeError('number required'); return value * 3; };\n*** Update File: index.test.cjs\n@@\n-test('numeric and rejection',()=>{assert.equal(double(4),8);assert.throws(()=>double('4'),TypeError);});\n+test('numeric and rejection',()=>{assert.equal(double(4),12);assert.throws(()=>double('4'),TypeError);});\n*** End Patch"}},{name:'bash',args:{command:'node --test',description:'Check numeric change and preserved rejection',timeout:90000}}];call=sequence[state.author++];}
 const id='resp_installed_'+(++seq),item=call?{id:'fc_'+seq,type:'function_call',call_id:'call_'+seq,name:call.name,arguments:JSON.stringify(call.args),status:'completed'}:{id:'msg_'+seq,type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:'Local fixture complete.',annotations:[]}]};
 const base={id,object:'response',created_at:1,model:body.model,status:'in_progress',output:[]};const events=[{type:'response.created',response:base},{type:'response.output_item.added',output_index:0,item:call?{...item,arguments:'',status:'in_progress'}:{...item,status:'in_progress',content:[]}}];
 if(call)events.push({type:'response.function_call_arguments.delta',item_id:item.id,output_index:0,delta:item.arguments});else events.push({type:'response.content_part.added',item_id:item.id,output_index:0,content_index:0,part:{type:'output_text',text:'',annotations:[]}},{type:'response.output_text.delta',item_id:item.id,output_index:0,content_index:0,delta:item.content[0].text});
 events.push({type:'response.output_item.done',output_index:0,item},{type:'response.completed',response:{...base,status:'completed',output:[item],usage:{input_tokens:1,output_tokens:1,total_tokens:2}}});
 const bytes=Buffer.from(events.map(e=>'data: '+JSON.stringify(e)+'\n\n').join(''));responses.push({slot:active.slot,bytes});res.writeHead(200,{'content-type':'text/event-stream','x-request-id':id});res.end(bytes);
 }catch(e){errors.push(e.message);res.writeHead(500);res.end('scripted assertion failed');}});
await new Promise(r=>provider.listen(0,'127.0.0.1',r));
try{
 const capture=(session,out)=>{const r=captureCandidate(session,out);assert.equal(r.status,0,JSON.stringify(r));const native=JSON.parse(fs.readFileSync(out+'/native-evidence.json'));const workflow=JSON.parse(native.tools.find(t=>t.data.tool==='harness_task').data.state.output);assert.deepEqual(workflow.stages.map(x=>[x.role,x.label]),[['author','implementation']]);assert.equal(workflow.repairs,0);const observation=session.exec(['node','-e',`const fs=require('fs');const p=${JSON.stringify(workflow.executionDirectory)};console.log(fs.readFileSync(require('path').dirname(p)+'/terminal.patch','utf8'));`]);assert.equal(observation.status,0,observation.stderr);assert.equal(observation.stdout.trimEnd(),fs.readFileSync(out+'/model.patch','utf8').trimEnd());assert.equal(state.author,4);return r;};capture.requiresOutputRetention=true;
 const result=await runComparison({root,startContainer:async options=>{active=attempts.find(a=>a.source===options.source);state={parent:0,author:0};const s=await startContainer({...options,workMemoryMb:1536,memoryMb:3072});s.baseline=s.exec(['git','rev-parse','HEAD']).stdout.trim();s.arm='H1';s.preparedEnvironment={projectPath:'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'};assert.equal(s.exec(['node','-e',"require('fs').writeFileSync('/work/config/project-shell.sh','true\\n')"]).status,0);return s;},captureCandidate:capture,stopWorkload,readAuth:()=>({access:'scripted-not-a-credential',accountId:'local'}),fetchImpl:async(url,options)=>{assert.equal(url,'https://chatgpt.com/backend-api/codex/responses');return fetch('http://127.0.0.1:'+provider.address().port,options);},runTaskImplementation:async(s,o)=>{const r=await installedTask(s,{...o,arm:'AR1'});return {exitCode:r.exitCode,termination:r.termination,timedOut:r.timedOut,nativeCompleted:r.exitCode===0,elapsedMs:r.elapsedMs};}});
 assert.deepEqual(errors,[]);assert.equal(result.status,'finished',JSON.stringify(result));
 for(const a of attempts){const out=root+'/runs/'+a.task+'-'+a.arm,records=JSON.parse(fs.readFileSync(out+'/provider-metadata.json')),sent=responses.filter(r=>r.slot===a.slot);assert.equal(records.length,sent.length);let bytes=0;
 for(const [i,r]of records.entries()){assert.equal(r.recording.evidenceComplete,true);assert.ok(fs.readFileSync(out+'/response-'+r.requestIndex+'.sse').equals(sent[i].bytes));bytes+=r.recording.response.size;}
 const name=JSON.parse(fs.readFileSync(out+'/session/container.json')).name;const inspect=spawnSync('docker',['inspect',name],{encoding:'utf8'});assert.notEqual(inspect.status,0);assert.match(inspect.stderr,/no such object/i);
 const checkout=root+'/apply-'+a.slot;fs.cpSync(a.source,checkout,{recursive:true});for(const args of [['init','-q'],['add','.'],['-c','user.name=Fixture','-c','user.email=fixture@localhost','commit','-qm','baseline'],['apply',out+'/model.patch']]){const r=spawnSync('git',args,{cwd:checkout,encoding:'utf8'});assert.equal(r.status,0,r.stderr);}const test=spawnSync(process.execPath,['--test'],{cwd:checkout,encoding:'utf8'});assert.equal(test.status,0,test.stdout+test.stderr);const acceptance=spawnSync(process.execPath,['-e',"const a=require('node:assert/strict'),{double}=require('./index.cjs');a.equal(double(5),15);a.throws(()=>double('5'),TypeError)"],{cwd:checkout,encoding:'utf8'});assert.equal(acceptance.status,0,acceptance.stderr);
 summaries.push({slot:a.slot,requests:records.length,responseBytes:bytes,requestBytes:records.reduce((n,r)=>n+r.recording.clientRequest.size+r.recording.upstreamRequest.size,0),storageMs:JSON.parse(fs.readFileSync(out+'/recording-'+records.length+'.json')).storageMs,oneAuthorStage:true,patchApplies:true,testsPass:true,sourceRemoved:true});}
 fs.writeFileSync(root+'/result.json',JSON.stringify({passed:true,elapsedMs:Date.now()-started,scriptedRequests:seq,authorRequests:authorPrompts.length,results:summaries,realProviderCalls:0},null,2));console.log(JSON.stringify({passed:true,root,scriptedRequests:seq,results:summaries}));
}finally{provider.closeAllConnections();await new Promise(r=>provider.close(r));fs.writeFileSync(root+'/attempt.json',JSON.stringify({requests:seq,errors,elapsedMs:Date.now()-started},null,2));}
