// Freeze the two prepared inputs for the existing scheduler. No provider call.
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
const root=path.resolve(process.argv[2]),publicRoot=path.resolve('development/native-task-sensitivity/replay-20260914');
const read=p=>JSON.parse(fs.readFileSync(p)),sha=b=>createHash('sha256').update(b).digest('hex');
if(fs.existsSync(root+'/freeze.json'))throw Error('Frozen inputs must not be replaced');
const candidate={runtimeSha:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim()},inputs=read(root+'/attempt-inputs.json'),attempts=inputs.flatMap((a,i)=>(i===0?['S0','S1']:['S1','S0']).map((arm,j)=>({...a,arm,slot:i*2+j+1}))),toolchain=read('local/native-task-h00-transfer/freeze.json').toolchain;
const installed=read(root+'/installed-preflight-denque.json'),modulePreflight=read(root+'/installed-preflight.json'),cancel=read(root+'/installed-preflight-cancel.json');
if(!modulePreflight.passed||!modulePreflight.results.every(r=>r.nativeCompleted))throw Error('Module preflight missing');
if(!installed.passed||installed.realProviderRequests!==0||!installed.results.every(r=>r.nativeCompleted&&r.termination.terminationVerified))throw Error('Installed preflight missing');
if(!cancel.passed||cancel.realProviderRequests!==0||!cancel.results.every(r=>r.diagnosticChildTerminated&&r.stopReason.kind==='cancelled'&&r.termination.terminationVerified))throw Error('Cancellation preflight missing');
const names=execFileSync('docker',['ps','--format','{{.Names}}'],{encoding:'utf8'}).trim().split('\n');if(names.some(n=>n.startsWith('template-dev-')))throw Error('Existing development execution');
function manifest(dir){const out={};const walk=(d,p='')=>{for(const e of fs.readdirSync(d,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){if(e.name==='.git')continue;const file=path.join(d,e.name),name=p+e.name,st=fs.lstatSync(file);if(st.isDirectory())walk(file,name+'/');else if(st.isSymbolicLink()){const link=fs.readlinkSync(file);if(path.isAbsolute(link)||!path.resolve(path.dirname(file),link).startsWith(dir+path.sep))throw Error('External symlink');out[name]={symlink:link};}else if(st.isFile())out[name]={sha256:sha(fs.readFileSync(file)),executable:!!(st.mode&0o111)};else throw Error('Unsupported file');}};walk(dir);return out;}
const inputManifests={},baseManifests={},files={};
for(const a of attempts){
 if(sha(fs.readFileSync(a.seedPatch))!==a.seedSha256)throw Error('Seed changed');
 const base=manifest(a.source);baseManifests[a.task]=base;
 const copy=fs.mkdtempSync(path.join(os.tmpdir(),'sensitivity-usage-freeze-'));
 try{fs.cpSync(a.source,copy,{recursive:true,verbatimSymlinks:true,filter:f=>!path.relative(a.source,f).split(path.sep).includes('node_modules')});execFileSync('git',['init','-q'],{cwd:copy});execFileSync('git',['apply','--check',a.seedPatch],{cwd:copy});execFileSync('git',['apply',a.seedPatch],{cwd:copy});inputManifests[a.task+'-'+a.arm]={...Object.fromEntries(Object.entries(base).filter(([n])=>n.startsWith('node_modules/'))),...manifest(copy)};}finally{fs.rmSync(copy,{recursive:true,force:true});}
 files[a.seedPatch]=a.seedSha256;files[a.source+'/TASK.md']=sha(fs.readFileSync(a.source+'/TASK.md'));
}
const bundle=root+'/bundle';for(const n of fs.readdirSync(bundle).filter(n=>n.endsWith('.mjs'))){const expected=execFileSync('git',['show',candidate.runtimeSha+':lib/'+n]);if(!expected.equals(fs.readFileSync(bundle+'/'+n)))throw Error('Candidate runtime differs: '+n);}
for(const name of ['development/native-task-sensitivity/run.mjs','development/native-task-ab/run-comparison.mjs','development/native-task-ab/native-run.mjs','development/native-task-ab/container-session.mjs','development/native-task-ab/container-relay.mjs','development/native-task-ab/capture-candidate.mjs','development/native-task-ab/extract-candidate.py','development/native-task-abc/native-run.mjs','development/native-task-utility/container/stop-workload.mjs','development/native-task-h00-transfer/evaluation-cases.mjs','development/native-task-sensitivity/replay-20260914/PLAN.md','development/native-task-sensitivity/replay-20260914/freeze.mjs','development/native-task-sensitivity/usage-20260914/prepare-inputs.mjs','development/native-task-sensitivity/replay-20260914/prepare.mjs','development/native-task-ab/preflight.mjs'])files[path.resolve(name)]=sha(fs.readFileSync(name));
for(const name of ['installed-preflight.json','installed-preflight-denque.json','installed-preflight-cancel.json','preflight-denque-final-evidence.json','preflight-module-final-evidence.json','review.json'])files[root+'/'+name]=sha(fs.readFileSync(root+'/'+name));
const s0=manifest(root+'/baseline'),s1=manifest(bundle),different=Object.keys(s1).filter(n=>JSON.stringify(s0[n])!==JSON.stringify(s1[n]));
if(different.sort().join(',')!=='native-sensitivity-runner.mjs,native-sensitivity.mjs,native-task-plugin.mjs'||Object.keys(s0).length!==Object.keys(s1).length)throw Error('Unexpected arm difference');
for(const name of different){const expected=execFileSync('git',['show','a91557782f71d4f546743d33d16cea4a571f86d4:lib/'+name]);if(!expected.equals(fs.readFileSync(root+'/baseline/'+name)))throw Error('S0 differs from previous sensitivity');}
const preservation={};for(const name of ['scheduling-paused.json','outcome.json']){const p=path.resolve('local/native-sensitivity/usage-20260914',name);files[p]=sha(fs.readFileSync(p));preservation[name]=files[p];}
fs.writeFileSync(root+'/historical-preservation.json',JSON.stringify(preservation,null,2));
const freeze={version:1,experimentKind:'sensitivity-replay',createdAt:new Date().toISOString(),runtimeSha:candidate.runtimeSha,executionHarnessSha:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),model:'openai/gpt-5.6-luna',variant:'high',budgetMs:900000,strategy:'direct',preflightPassed:true,streamLimit:'remaining-task-budget',connectionTimeoutMs:30000,toolchain,template:bundle,baselineTemplate:root+'/baseline',dependencies:bundle,config:read(root+'/experiment-config.json'),attempts,inputManifests,baseManifests,files,runtimeManifests:{[bundle]:manifest(bundle),[root+'/baseline']:manifest(root+'/baseline')}};
fs.writeFileSync(root+'/freeze.json',JSON.stringify(freeze),{flag:'wx'});
fs.writeFileSync(publicRoot+'/frozen-inputs.json',JSON.stringify({kind:freeze.experimentKind,createdAt:freeze.createdAt,runtimeSha:freeze.runtimeSha,executionHarnessSha:freeze.executionHarnessSha,freezeSha256:sha(fs.readFileSync(root+'/freeze.json')),image:installed.results[0].termination?read(root+'/preflight-denque-final-H1/container.json').image:null,model:freeze.model,variant:freeze.variant,budgetMs:freeze.budgetMs,diagnosticBudgetMs:180000,variants:8,bundleManifestSha256:sha(JSON.stringify(freeze.runtimeManifests[bundle])),baselineBundleManifestSha256:sha(JSON.stringify(freeze.runtimeManifests[root+'/baseline'])),inputs:attempts.map(a=>({slot:a.slot,case:a.task,arm:a.arm,fullTask:fs.readFileSync(a.source+'/TASK.md','utf8'),seedPatch:path.relative(process.cwd(),a.seedPatch),seedSha256:a.seedSha256,taskSha256:files[a.source+'/TASK.md'],baseTreeManifestSha256:sha(JSON.stringify(baseManifests[a.task])),patchedTreeManifestSha256:sha(JSON.stringify(inputManifests[a.task+'-'+a.arm]))})),realProviderRequestsBeforeFreeze:0},null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({frozen:true,attempts:4,runtimeSha:freeze.runtimeSha,realProviderRequests:0}));
