// Compact public observations; raw sessions and complete projects stay local.
import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';
const root=path.resolve(process.argv[2]),pub=path.resolve('development/native-task-sensitivity/replay-20260914'),read=p=>JSON.parse(fs.readFileSync(p)),sha=b=>createHash('sha256').update(b).digest('hex');
const f=read(root+'/freeze.json');if(!['finished','paused'].includes(read(root+'/outcome.json').status))throw Error('Both attempts must be retained and stopped');
const review=read(pub+'/assessment.json');const rows=[];
fs.mkdirSync(pub+'/attempts',{recursive:true});fs.mkdirSync(pub+'/patches',{recursive:true});
const sum=(xs,key)=>xs.reduce((n,x)=>n+(Number.isFinite(x[key])?x[key]:0),0);
for(const a of f.attempts){
 const dir=root+'/runs/'+a.task+'-'+a.arm;if(!fs.existsSync(dir))continue;
 const r=read(dir+'/result.json'),stop=read(dir+'/stop-verification.json'),native=read(dir+'/native-evidence.json'),metadata=read(dir+'/provider-metadata.json');
 if(!stop.terminationVerified||!stop.relayRemoved||stop.activeProviderHandlers!==0)throw Error('Stop unverified');
 const taskRoot=dir+'/candidate/.git/harness-task',id=fs.readdirSync(taskRoot).find(n=>fs.existsSync(taskRoot+'/'+n+'/worktree')),artifacts=taskRoot+'/'+id;
 const workflow=read(artifacts+'/result.json'),events=read(artifacts+'/tool-events.json'),senseFile=artifacts+'/sensitivity-events.json';
 const observations=fs.existsSync(senseFile)?read(senseFile):[];
 const requests=fs.readdirSync(dir).filter(n=>/^request-\d+\.json$/.test(n)).sort((a,b)=>Number(a.match(/\d+/)[0])-Number(b.match(/\d+/)[0])).map(n=>read(dir+'/'+n));
 const authorRequests=requests.filter(j=>(j.input??[]).some(x=>x.role==='user'&&JSON.stringify(x.content).includes('Implement the complete original task')));
 const advertised=authorRequests.length>0&&authorRequests.every(j=>j.tools.some(t=>t.name==='harness_sense'));
 const selected=metadata.filter(m=>m.forwarded),usages=selected.filter(m=>m.usage).map(m=>m.usage);
 const usage={providerRequests:selected.length,requestsWithoutUsage:selected.filter(m=>!m.usage).length,inputTokens:sum(usages,'input_tokens'),outputTokens:sum(usages,'output_tokens'),totalTokens:sum(usages,'total_tokens'),cachedInputTokens:sum(usages,'cached_tokens'),reasoningTokens:sum(usages,'reasoning_tokens'),cachedSubsetUnknownRequests:selected.filter(m=>!Number.isFinite(m.usage?.cached_tokens)).length,reasoningSubsetUnknownRequests:selected.filter(m=>!Number.isFinite(m.usage?.reasoning_tokens)).length};
 const diagnostics=observations.map(e=>{const report=JSON.parse(e.output);return {callID:e.callID,originalArguments:e.originalArguments,selectedVariant:report.selectedVariant??null,snapshot:report.snapshot,tests:report.tests??null,command:report.command??null,status:report.status,engineExecuted:report.engineExecuted,baseline:report.baseline,sourceState:e.sourceState,stale:e.stale,elapsedMs:e.elapsedMs,taskDiagnosticMs:e.taskDiagnosticMs,cost:report.cost,terminationVerified:report.terminationVerified,limits:report.limits,variants:report.variants.map(m=>({ref:m.ref??null,output:m.output,sourceSha256:m.sourceSha256??null,file:m.fileName,operator:m.mutatorName,diff:m.diff,status:m.status,exit:m.exit,interpretation:m.interpretation}))};});
 const patch=fs.readFileSync(root+'/checks/'+a.task+'-'+a.arm+'/verified.patch'),patchFile='patches/'+String(a.slot).padStart(2,'0')+'-'+a.task+'-'+a.arm+'.patch';fs.writeFileSync(pub+'/'+patchFile,patch);
 const verification=read(root+'/checks/'+a.task+'-'+a.arm+'/verification.json');
 const timeline=events.map((e,i)=>({index:i+1,callID:e.callID,tool:e.tool,state:e.state,exit:e.exit??null,startedAt:e.startedAt,completedAt:e.completedAt,changedState:e.before!==e.after,action:(e.args?.command??e.args?.filePath??e.args?.path??(e.tool==='apply_patch'?'apply project patch':'')).replaceAll(/\/work\/repo\/\.git\/harness-task\/[^/]+\/worktree/g,'<task-worktree>').slice(0,200)}));
 const authorSummary=fs.existsSync(artifacts+'/implementation-original.json')?read(artifacts+'/implementation-original.json').parts.filter(p=>p.type==='text').map(p=>p.text).join('\n'):null;
 const row={slot:a.slot,case:a.task,arm:a.arm,runtimeSha:f.runtimeSha,advertisedInAllAuthorRequests:advertised,authorRequests:authorRequests.length,diagnosticCalls:diagnostics.length,diagnostics,timeline,authorSummary,patch:patchFile,patchSha256:sha(patch),nativeCompleted:r.nativeCompleted,nativeExit:r.exitCode,stopReason:r.stopReason,phaseCount:r.phaseCount,nativeSessions:native.sessions.length,authorSessions:native.sessions.filter(s=>s.parent_id).length,toolCalls:native.tools.length,workflowStatus:r.workflowStatus,capturedWorkflowStatus:workflow.status,workflowRepairs:r.repairs,completedCommands:workflow.completedCommands,termination:stop,usage,unknownRequests:selected.filter(m=>!m.usage).map(m=>({requestIndex:m.requestIndex,status:m.status??null,error:m.error??null,responseStatus:m.responseStatus??null,serverCompletion:m.serverCompletion??null,forwardedAt:m.forwardedAt,finishedAt:m.finishedAt})),executionElapsedMs:r.executionElapsedMs,cleanupElapsedMs:r.cleanupElapsedMs,preparationAndCaptureElapsedMs:Date.parse(read(dir+'/completed.json').at)-Date.parse(read(dir+'/started.json').at)-r.elapsedMs,ordinary:verification.ordinary,independent:verification.independent,offlineSensitivity:{...verification.offline,variants:verification.offline.variants.map(({output,...m})=>m)},changedFromSeed:verification.changedFromSeed,patchKind:verification.patchKind,terminalApplicable:verification.terminalApplicable,review:review[a.task+'-'+a.arm]};
 fs.writeFileSync(pub+'/attempts/'+String(a.slot).padStart(2,'0')+'-requests.json',JSON.stringify(metadata.map(m=>({requestIndex:m.requestIndex,requestKind:m.requestKind,forwarded:m.forwarded,status:m.status??null,forwardedAt:m.forwardedAt,finishedAt:m.finishedAt,usage:m.usage??null,serverCompletion:m.serverCompletion??null,error:m.error??null,requestSha256:sha(fs.readFileSync(dir+'/request-'+m.requestIndex+'.json'))})),null,2)+'\n');rows.push(row);fs.writeFileSync(pub+'/attempts/'+String(a.slot).padStart(2,'0')+'.json',JSON.stringify(row,null,2)+'\n');
}
const totals={attempts:rows.length,providerRequests:sum(rows.map(r=>r.usage),'providerRequests'),unknownUsageRequests:sum(rows.map(r=>r.usage),'requestsWithoutUsage'),inputTokens:sum(rows.map(r=>r.usage),'inputTokens'),outputTokens:sum(rows.map(r=>r.usage),'outputTokens'),totalTokens:sum(rows.map(r=>r.usage),'totalTokens'),cachedInputTokens:sum(rows.map(r=>r.usage),'cachedInputTokens'),reasoningTokens:sum(rows.map(r=>r.usage),'reasoningTokens'),toolCalls:sum(rows,'toolCalls'),diagnosticCalls:sum(rows,'diagnosticCalls'),executionElapsedMs:sum(rows,'executionElapsedMs'),cleanupElapsedMs:sum(rows,'cleanupElapsedMs'),preparationAndCaptureElapsedMs:sum(rows,'preparationAndCaptureElapsedMs')};
const reports=rows.flatMap(r=>r.diagnostics.map(d=>d.cost));
const costs={modelRuns:totals,authorDiagnostics:{commands:sum(reports,'commands'),engineMs:sum(reports,'engineMs'),preparationMs:sum(reports,'preparationMs'),commandMs:sum(reports,'commandMs'),totalMs:sum(reports,'totalMs')},offlineVerification:{ordinaryAndIndependentMs:rows.reduce((n,r)=>n+r.ordinary.elapsedMs+r.independent.elapsedMs,0),sensitivity:rows.map(r=>({case:r.case,arm:r.arm,cost:r.offlineSensitivity.cost}))},preparationAdmission:[...new Set(f.attempts.map(a=>a.task))].map(task=>({case:task,cost:read(root+'/admission/'+task+'/report.json').cost})),scope:'Cache and reasoning are subsets, not added again. Diagnostic execution is inside native elapsed time. Offline checks are separate and not author actions.',installedPreflight:{runs:fs.readdirSync(root).filter(n=>/^preflight.*-H1$/.test(n)&&fs.existsSync(root+'/'+n+'/finished.json')).map(name=>({name,...read(root+'/'+name+'/finished.json'),fixturePassed:!['preflight-denque-H1','preflight-denque-fixed-H1'].includes(name)})),deliveryMs:read(root+'/installed-preflight.json').results[0].elapsedMs,knownExampleMs:read(root+'/installed-preflight-denque.json').results[0].elapsedMs,cancellationMs:read(root+'/installed-preflight-cancel.json').results[0].elapsedMs,realProviderRequests:0},aggregateDeveloperPreparationMs:null,monetaryCost:null};
const arms=Object.fromEntries(['S0','S1'].map(arm=>{const selected=rows.filter(r=>r.arm===arm);return [arm,{attempts:selected.length,Q:selected.filter(r=>r.review.Q).length,D:selected.filter(r=>r.review.D).length,completeCorrectAutonomous:selected.filter(r=>r.review.Q&&r.review.D).length,usefulAuthorChain:selected.filter(r=>r.review.usefulAuthorChain).length,executionElapsedMs:sum(selected,'executionElapsedMs'),knownTokens:sum(selected.map(r=>r.usage),'totalTokens'),unknownUsageRequests:sum(selected.map(r=>r.usage),'requestsWithoutUsage')}];}));
const helpful=rows.length===4&&arms.S1.completeCorrectAutonomous>arms.S0.completeCorrectAutonomous&&arms.S1.usefulAuthorChain>0&&rows.find(r=>r.case==='case-2'&&r.arm==='S1').review.Q;
fs.writeFileSync(pub+'/costs.json',JSON.stringify(costs,null,2)+'\n');
fs.writeFileSync(pub+'/results.json',JSON.stringify({kind:'four-run-selected-development-replay-comparison',outcome:read(root+'/outcome.json'),runtimeSha:f.runtimeSha,baselineRuntimeSha:'a91557782f71d4f546743d33d16cea4a571f86d4',executionHarnessSha:f.executionHarnessSha,model:f.model,effort:f.variant,budgetMs:f.budgetMs,rows:rows.map(({timeline,diagnostics,offlineSensitivity,...r})=>r),totals,arms,mechanismPracticallyHelped:helpful,sustainedQualityAdvantageEstablished:false,replacements:0,additionalRealSmokes:0,historicalResultsUnchanged:true},null,2)+'\n');console.log(JSON.stringify({totals,arms,mechanismPracticallyHelped:helpful}));
